/**
 * Supabase Database Types
 *
 * AUTO-GENERATED by scripts/generate-schema-types.mjs
 * Generated at: 2026-03-17T00:59:45.603Z
 *
 * SPRINT-045-SCHEMA-TYPE-SYNC: Updated with all canonical V3 tables and lifecycle columns.
 *
 * NOTE: In production with Supabase CLI access, regenerate with:
 *   npx supabase gen types typescript --project-id <id> > packages/shared-types/src/supabase.ts
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// Row interfaces for each table
interface UnifiedPicksRow {
  id: string;
  created_at: string;
  updated_at: string;
  player_name: string | null;
  sport: string | null;
  league: string | null;
  stat_type: string | null;
  line: number | null;
  odds: number | null;
  stake: number | null;
  payout: number | null;
  direction: string | null;
  capper: string | null;
  capper_id: string | null;
  player_id: string | null;
  game_id: string | null;
  tier: string | null;
  confidence: number | null;
  professional_score: number | null;
  result: string | null;
  actual_value: number | null;
  source: string | null;
  promotion_status: string | null;
  promotion_band: string | null;
  promotion_queued_at: string | null;
  promotion_posted_at: string | null;
  posted_to_discord: boolean;
  discord_message_id: string | null;
  discord_thread_id: string | null;
  discord_post_id: string | null;
  status: string | null;
  settlement_status: string | null;
  settlement_result: string | null;
  settlement_source: string | null;
  settled_at: string | null;
  settlement_version: number | null;
  settlement_hash: string | null;
  settlement_frozen: boolean | null;
  freeze_enforced_at: string | null;
  lifecycle_stage: string | null;
  bet_slip_id: string | null;
  ticket_type: string | null;
  parlay_id: string | null;
  blocked_reason: string | null;
  failed_reason: string | null;
  blocked_at: string | null;
  failed_at: string | null;
  placed_at: string | null;
  meta: Record<string, unknown> | null;
}

interface ParticipantsRow {
  id: string;
  created_at: string;
  updated_at: string;
  name: string;
  type: string;
  sport: string | null;
  league: string | null;
  external_id: string | null;
  provider: string | null;
  meta: Record<string, unknown> | null;
  active: boolean;
}

interface ParticipantMembershipsRow {
  id: string;
  created_at: string;
  player_id: string;
  team_id: string;
  start_date: string | null;
  end_date: string | null;
  role: string | null;
  meta: Record<string, unknown> | null;
}

interface EventsRow {
  id: string;
  created_at: string;
  updated_at: string;
  sport: string | null;
  league: string | null;
  scheduled_at: string | null;
  home_participant_id: string | null;
  away_participant_id: string | null;
  status: string | null;
  external_id: string | null;
  provider: string | null;
  event_data: Record<string, unknown> | null;
  meta: Record<string, unknown> | null;
}

interface MarketsRow {
  id: string;
  created_at: string;
  stat_type: string;
  canonical_key: string;
  sport: string | null;
  display_name: string | null;
  category: string | null;
  meta: Record<string, unknown> | null;
}

interface ProviderOffersRow {
  id: string;
  created_at: string;
  snapshot_at: string;
  event_id: string | null;
  market_id: string | null;
  participant_id: string | null;
  provider: string | null;
  provider_market_key: string | null;
  line: number | null;
  over_odds: number | null;
  under_odds: number | null;
  is_closing: boolean;
  graded_at: string | null;
  meta: Record<string, unknown> | null;
}

interface TicketsRow {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string | null;
  ticket_type: string | null;
  status: string | null;
  source: string | null;
  meta: Record<string, unknown> | null;
}

interface TicketLegsRow {
  id: string;
  created_at: string;
  ticket_id: string;
  event_id: string | null;
  market_id: string | null;
  participant_id: string | null;
  line: number | null;
  odds: number | null;
  direction: string | null;
  stat_type: string | null;
  player_name: string | null;
  meta: Record<string, unknown> | null;
}

interface FeatureSnapshotsRow {
  id: string;
  created_at: string;
  leg_id: string;
  features: Record<string, unknown> | null;
  model_version: string | null;
}

interface ScoredLegsRow {
  id: string;
  created_at: string;
  leg_id: string;
  feature_snapshot_id: string | null;
  score: number | null;
  tier: string | null;
  promotion_band: string | null;
  model_version: string | null;
  meta: Record<string, unknown> | null;
}

interface PropSettlementsRow {
  id: string;
  created_at: string;
  final_pick_id: string | null;
  settlement_status: string | null;
  settlement_result: string | null;
  actual_outcome: number | null;
  settlement_source: string | null;
  meta: Record<string, unknown> | null;
}

interface SettlementAuditLogRow {
  id: string;
  pick_id: string;
  prop_settlement_id: string | null;
  prev_settlement: Record<string, unknown> | null;
  new_settlement: Record<string, unknown>;
  prev_hash: string | null;
  new_hash: string;
  action_type: string;
  changed_by: string;
  reason: string | null;
  idempotency_key: string;
  trace_id: string | null;
  created_at: string;
}

interface ClosingSnapshotsRow {
  id: string;
  created_at: string;
  event_id: string | null;
  market_type_id: number | null;
  market_key: string | null;
  consensus_line: number | null;
  devigged_over: number | null;
  devigged_under: number | null;
  snapshot_count: number | null;
  meta: Record<string, unknown> | null;
}

interface ClvResultsRow {
  id: string;
  created_at: string;
  pick_id: string;
  model_version: string | null;
  close_kind: string | null;
  clv_edge: number | null;
  entry_ev: number | null;
  close_ev: number | null;
  meta: Record<string, unknown> | null;
}

interface BridgeOutboxRow {
  id: string;
  created_at: string;
  event_type: string;
  payload: Record<string, unknown> | null;
  status: string;
  processed_at: string | null;
}

interface AgentHealthRow {
  id: string;
  created_at: string;
  agent_name: string;
  status: string;
  last_heartbeat: string;
  metadata: Record<string, unknown> | null;
}

interface UsersRow {
  id: string;
  created_at: string;
  updated_at: string;
  email: string | null;
  role: string | null;
  display_name: string | null;
  status: string | null;
  active: boolean | null;
}

interface CappersRow {
  id: string;
  created_at: string;
  user_id: string | null;
  name: string | null;
  display_name: string | null;
  meta: Record<string, unknown> | null;
}

interface AuditLogRow {
  id: string;
  created_at: string;
  action: string | null;
  entity_type: string | null;
  entity_id: string | null;
  actor_id: string | null;
  details: Record<string, unknown> | null;
}

interface SmartTicketsRow {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string | null;
  sport: string | null;
  status: string | null;
  payload: Record<string, unknown> | null;
}

interface UserProfilesRow {
  id: string;
  created_at: string;
  updated_at: string;
  user_id: string | null;
  preferences: Record<string, unknown> | null;
}

interface TicketDiscordOutboxRow {
  id: string;
  created_at: string;
  ticket_id: string | null;
  status: string | null;
  channel_id: string | null;
  claimed_by: string | null;
  claimed_at: string | null;
  posted_at: string | null;
  meta: Record<string, unknown> | null;
}

interface PlayerProjectionsRow {
  id: string;
  created_at: string;
  player_id: string | null;
  stat_type: string | null;
  projected_value: number | null;
  source: string | null;
  meta: Record<string, unknown> | null;
}

interface OpsWorkerHeartbeatsRow {
  id: string;
  created_at: string;
  worker_name: string;
  last_heartbeat_at: string;
  status: string | null;
  metadata: Record<string, unknown> | null;
}

interface AutopilotDecisionsRow {
  id: string;
  created_at: string;
  action: string | null;
  mode: string | null;
  decision: string | null;
  reason: string | null;
  evidence_id: string | null;
  meta: Record<string, unknown> | null;
}

interface AutopilotPolicyConfigRow {
  id: string;
  created_at: string;
  updated_at: string;
  policy_key: string | null;
  policy_value: string | null;
  description: string | null;
}

interface AutopilotCooldownsRow {
  id: string;
  created_at: string;
  action: string | null;
  cooldown_until: string | null;
  meta: Record<string, unknown> | null;
}

interface RiskEngineConfigRow {
  id: string;
  created_at: string;
  updated_at: string;
  config_key: string | null;
  config_value: number | null;
  description: string | null;
  updated_by: string | null;
}

interface RiskEventsRow {
  id: string;
  created_at: string;
  event_type: string | null;
  severity: string | null;
  pick_id: string | null;
  exposure_snapshot: Record<string, unknown> | null;
  drift_snapshot: Record<string, unknown> | null;
  config_snapshot: Record<string, unknown> | null;
  meta: Record<string, unknown> | null;
}

interface ApiCreditLogRow {
  id: string;
  created_at: string;
  provider: string | null;
  sport: string | null;
  credits_used: number | null;
  meta: Record<string, unknown> | null;
}

interface ExecutionEventsRow {
  id: string;
  created_at: string;
  event_type: string | null;
  agent_name: string | null;
  correlation_id: string | null;
  payload: Record<string, unknown> | null;
  duration_ms: number | null;
}

interface ShadowScoresRow {
  id: string;
  created_at: string;
  pick_id: string | null;
  model_version: string | null;
  v1_score: number | null;
  v2_score: number | null;
  divergence: number | null;
  meta: Record<string, unknown> | null;
}

interface OutcomeRecordsRow {
  id: string;
  created_at: string;
  pick_id: string | null;
  event_id: string | null;
  actual_value: number | null;
  source: string | null;
  meta: Record<string, unknown> | null;
}

interface MarketPolicyRow {
  id: string;
  created_at: string;
  sport: string | null;
  stat_type: string | null;
  enabled: boolean;
  meta: Record<string, unknown> | null;
}

interface PublishOutboxRow {
  id: string;
  created_at: string;
  pick_id: string | null;
  status: string | null;
  channel: string | null;
  claimed_by: string | null;
  claimed_at: string | null;
  published_at: string | null;
  meta: Record<string, unknown> | null;
}

interface OperatorAuditLogRow {
  id: string;
  created_at: string;
  operator_id: string;
  operator_email: string | null;
  action: string;
  endpoint: string;
  method: string;
  request_body: Record<string, unknown> | null;
  response_status: number | null;
  ip_address: string | null;
  user_agent: string | null;
  duration_ms: number | null;
  meta: Record<string, unknown> | null;
}

export interface Database {
  public: {
    Tables: {
      unified_picks: {
        Row: UnifiedPicksRow;
        Insert: Partial<UnifiedPicksRow>;
        Update: Partial<UnifiedPicksRow>;
        Relationships: [];
      };
      participants: {
        Row: ParticipantsRow;
        Insert: Partial<ParticipantsRow>;
        Update: Partial<ParticipantsRow>;
        Relationships: [];
      };
      participant_memberships: {
        Row: ParticipantMembershipsRow;
        Insert: Partial<ParticipantMembershipsRow>;
        Update: Partial<ParticipantMembershipsRow>;
        Relationships: [];
      };
      events: {
        Row: EventsRow;
        Insert: Partial<EventsRow>;
        Update: Partial<EventsRow>;
        Relationships: [];
      };
      markets: {
        Row: MarketsRow;
        Insert: Partial<MarketsRow>;
        Update: Partial<MarketsRow>;
        Relationships: [];
      };
      provider_offers: {
        Row: ProviderOffersRow;
        Insert: Partial<ProviderOffersRow>;
        Update: Partial<ProviderOffersRow>;
        Relationships: [];
      };
      tickets: {
        Row: TicketsRow;
        Insert: Partial<TicketsRow>;
        Update: Partial<TicketsRow>;
        Relationships: [];
      };
      ticket_legs: {
        Row: TicketLegsRow;
        Insert: Partial<TicketLegsRow>;
        Update: Partial<TicketLegsRow>;
        Relationships: [];
      };
      feature_snapshots: {
        Row: FeatureSnapshotsRow;
        Insert: Partial<FeatureSnapshotsRow>;
        Update: Partial<FeatureSnapshotsRow>;
        Relationships: [];
      };
      scored_legs: {
        Row: ScoredLegsRow;
        Insert: Partial<ScoredLegsRow>;
        Update: Partial<ScoredLegsRow>;
        Relationships: [];
      };
      prop_settlements: {
        Row: PropSettlementsRow;
        Insert: Partial<PropSettlementsRow>;
        Update: Partial<PropSettlementsRow>;
        Relationships: [];
      };
      settlement_audit_log: {
        Row: SettlementAuditLogRow;
        Insert: Partial<SettlementAuditLogRow>;
        Update: Partial<SettlementAuditLogRow>;
        Relationships: [];
      };
      closing_snapshots: {
        Row: ClosingSnapshotsRow;
        Insert: Partial<ClosingSnapshotsRow>;
        Update: Partial<ClosingSnapshotsRow>;
        Relationships: [];
      };
      clv_results: {
        Row: ClvResultsRow;
        Insert: Partial<ClvResultsRow>;
        Update: Partial<ClvResultsRow>;
        Relationships: [];
      };
      bridge_outbox: {
        Row: BridgeOutboxRow;
        Insert: Partial<BridgeOutboxRow>;
        Update: Partial<BridgeOutboxRow>;
        Relationships: [];
      };
      agent_health: {
        Row: AgentHealthRow;
        Insert: Partial<AgentHealthRow>;
        Update: Partial<AgentHealthRow>;
        Relationships: [];
      };
      users: {
        Row: UsersRow;
        Insert: Partial<UsersRow>;
        Update: Partial<UsersRow>;
        Relationships: [];
      };
      cappers: {
        Row: CappersRow;
        Insert: Partial<CappersRow>;
        Update: Partial<CappersRow>;
        Relationships: [];
      };
      audit_log: {
        Row: AuditLogRow;
        Insert: Partial<AuditLogRow>;
        Update: Partial<AuditLogRow>;
        Relationships: [];
      };
      smart_tickets: {
        Row: SmartTicketsRow;
        Insert: Partial<SmartTicketsRow>;
        Update: Partial<SmartTicketsRow>;
        Relationships: [];
      };
      user_profiles: {
        Row: UserProfilesRow;
        Insert: Partial<UserProfilesRow>;
        Update: Partial<UserProfilesRow>;
        Relationships: [];
      };
      ticket_discord_outbox: {
        Row: TicketDiscordOutboxRow;
        Insert: Partial<TicketDiscordOutboxRow>;
        Update: Partial<TicketDiscordOutboxRow>;
        Relationships: [];
      };
      player_projections: {
        Row: PlayerProjectionsRow;
        Insert: Partial<PlayerProjectionsRow>;
        Update: Partial<PlayerProjectionsRow>;
        Relationships: [];
      };
      ops_worker_heartbeats: {
        Row: OpsWorkerHeartbeatsRow;
        Insert: Partial<OpsWorkerHeartbeatsRow>;
        Update: Partial<OpsWorkerHeartbeatsRow>;
        Relationships: [];
      };
      autopilot_decisions: {
        Row: AutopilotDecisionsRow;
        Insert: Partial<AutopilotDecisionsRow>;
        Update: Partial<AutopilotDecisionsRow>;
        Relationships: [];
      };
      autopilot_policy_config: {
        Row: AutopilotPolicyConfigRow;
        Insert: Partial<AutopilotPolicyConfigRow>;
        Update: Partial<AutopilotPolicyConfigRow>;
        Relationships: [];
      };
      autopilot_cooldowns: {
        Row: AutopilotCooldownsRow;
        Insert: Partial<AutopilotCooldownsRow>;
        Update: Partial<AutopilotCooldownsRow>;
        Relationships: [];
      };
      risk_engine_config: {
        Row: RiskEngineConfigRow;
        Insert: Partial<RiskEngineConfigRow>;
        Update: Partial<RiskEngineConfigRow>;
        Relationships: [];
      };
      risk_events: {
        Row: RiskEventsRow;
        Insert: Partial<RiskEventsRow>;
        Update: Partial<RiskEventsRow>;
        Relationships: [];
      };
      api_credit_log: {
        Row: ApiCreditLogRow;
        Insert: Partial<ApiCreditLogRow>;
        Update: Partial<ApiCreditLogRow>;
        Relationships: [];
      };
      execution_events: {
        Row: ExecutionEventsRow;
        Insert: Partial<ExecutionEventsRow>;
        Update: Partial<ExecutionEventsRow>;
        Relationships: [];
      };
      shadow_scores: {
        Row: ShadowScoresRow;
        Insert: Partial<ShadowScoresRow>;
        Update: Partial<ShadowScoresRow>;
        Relationships: [];
      };
      outcome_records: {
        Row: OutcomeRecordsRow;
        Insert: Partial<OutcomeRecordsRow>;
        Update: Partial<OutcomeRecordsRow>;
        Relationships: [];
      };
      market_policy: {
        Row: MarketPolicyRow;
        Insert: Partial<MarketPolicyRow>;
        Update: Partial<MarketPolicyRow>;
        Relationships: [];
      };
      publish_outbox: {
        Row: PublishOutboxRow;
        Insert: Partial<PublishOutboxRow>;
        Update: Partial<PublishOutboxRow>;
        Relationships: [];
      };
      operator_audit_log: {
        Row: OperatorAuditLogRow;
        Insert: Partial<OperatorAuditLogRow>;
        Update: Partial<OperatorAuditLogRow>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// Re-export for convenience
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
