/**
 * Supabase Database Types
 *
 * AUTO-GENERATED by scripts/generate-schema-types.mjs
 * Generated at: 2026-03-09T16:28:38.910Z
 *
 * SPRINT-SCHEMA-ENV-GATES-002: Baseline types for schema drift detection.
 *
 * NOTE: In production with Supabase CLI access, regenerate with:
 *   npx supabase gen types typescript --project-id <id> > packages/shared-types/src/supabase.ts
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// Row interfaces for each table
interface UnifiedPicksRow {
  id: string;
  created_at: string;
  updated_at: string;
  player_name: string | null;
  sport: string | null;
  stat_type: string | null;
  line: number | null;
  odds: number | null;
  direction: string | null;
  capper: string | null;
  tier: string | null;
  posted_to_discord: boolean;
  settlement_status: string | null;
  lifecycle_stage: string | null;
  bet_slip_id: string | null;
  ticket_type: string | null;
  meta: Record<string, unknown> | null;
}

interface BridgeOutboxRow {
  id: string;
  created_at: string;
  updated_at: string;
  event_type: string;
  payload: Record<string, unknown>;
  status: string;
  processed_at: string | null;
}

interface AgentHealthRow {
  id: string;
  created_at: string;
  updated_at: string;
  agent_name: string;
  status: string;
  last_heartbeat: string;
  metadata: Record<string, unknown> | null;
}

interface PropSettlementsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface UsersRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface RawPropsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface GamesRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface PlayersRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface ClosingSnapshotsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface AuditLogRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface CappersRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface SmartTicketsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface TeamsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface UserProfilesRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface TicketDiscordOutboxRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface PlayerProjectionsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface OpsWorkerHeartbeatsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface AutopilotDecisionsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface AutopilotPolicyConfigRow {
  id: string;
  created_at: string;
  updated_at: string;
}

interface AutopilotCooldownsRow {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface Database {
  public: {
    Tables: {
      unified_picks: {
        Row: UnifiedPicksRow;
        Insert: Partial<UnifiedPicksRow>;
        Update: Partial<UnifiedPicksRow>;
        Relationships: [];
      };
      bridge_outbox: {
        Row: BridgeOutboxRow;
        Insert: Partial<BridgeOutboxRow>;
        Update: Partial<BridgeOutboxRow>;
        Relationships: [];
      };
      agent_health: {
        Row: AgentHealthRow;
        Insert: Partial<AgentHealthRow>;
        Update: Partial<AgentHealthRow>;
        Relationships: [];
      };
      prop_settlements: {
        Row: PropSettlementsRow;
        Insert: Partial<PropSettlementsRow>;
        Update: Partial<PropSettlementsRow>;
        Relationships: [];
      };
      users: {
        Row: UsersRow;
        Insert: Partial<UsersRow>;
        Update: Partial<UsersRow>;
        Relationships: [];
      };
      raw_props: {
        Row: RawPropsRow;
        Insert: Partial<RawPropsRow>;
        Update: Partial<RawPropsRow>;
        Relationships: [];
      };
      games: {
        Row: GamesRow;
        Insert: Partial<GamesRow>;
        Update: Partial<GamesRow>;
        Relationships: [];
      };
      players: {
        Row: PlayersRow;
        Insert: Partial<PlayersRow>;
        Update: Partial<PlayersRow>;
        Relationships: [];
      };
      closing_snapshots: {
        Row: ClosingSnapshotsRow;
        Insert: Partial<ClosingSnapshotsRow>;
        Update: Partial<ClosingSnapshotsRow>;
        Relationships: [];
      };
      audit_log: {
        Row: AuditLogRow;
        Insert: Partial<AuditLogRow>;
        Update: Partial<AuditLogRow>;
        Relationships: [];
      };
      cappers: {
        Row: CappersRow;
        Insert: Partial<CappersRow>;
        Update: Partial<CappersRow>;
        Relationships: [];
      };
      smart_tickets: {
        Row: SmartTicketsRow;
        Insert: Partial<SmartTicketsRow>;
        Update: Partial<SmartTicketsRow>;
        Relationships: [];
      };
      teams: {
        Row: TeamsRow;
        Insert: Partial<TeamsRow>;
        Update: Partial<TeamsRow>;
        Relationships: [];
      };
      user_profiles: {
        Row: UserProfilesRow;
        Insert: Partial<UserProfilesRow>;
        Update: Partial<UserProfilesRow>;
        Relationships: [];
      };
      ticket_discord_outbox: {
        Row: TicketDiscordOutboxRow;
        Insert: Partial<TicketDiscordOutboxRow>;
        Update: Partial<TicketDiscordOutboxRow>;
        Relationships: [];
      };
      player_projections: {
        Row: PlayerProjectionsRow;
        Insert: Partial<PlayerProjectionsRow>;
        Update: Partial<PlayerProjectionsRow>;
        Relationships: [];
      };
      ops_worker_heartbeats: {
        Row: OpsWorkerHeartbeatsRow;
        Insert: Partial<OpsWorkerHeartbeatsRow>;
        Update: Partial<OpsWorkerHeartbeatsRow>;
        Relationships: [];
      };
      autopilot_decisions: {
        Row: AutopilotDecisionsRow;
        Insert: Partial<AutopilotDecisionsRow>;
        Update: Partial<AutopilotDecisionsRow>;
        Relationships: [];
      };
      autopilot_policy_config: {
        Row: AutopilotPolicyConfigRow;
        Insert: Partial<AutopilotPolicyConfigRow>;
        Update: Partial<AutopilotPolicyConfigRow>;
        Relationships: [];
      };
      autopilot_cooldowns: {
        Row: AutopilotCooldownsRow;
        Insert: Partial<AutopilotCooldownsRow>;
        Update: Partial<AutopilotCooldownsRow>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// Re-export for convenience
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
