import { z } from 'zod';
export declare const RawPropSchema: z.ZodObject<{
    scraped_at: z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
    edge_score: z.ZodNullable<z.ZodNumber>;
    auto_approved: z.ZodNullable<z.ZodBoolean>;
    context_flag: z.ZodNullable<z.ZodBoolean>;
    created_at: z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
    promoted_to_picks: z.ZodNullable<z.ZodBoolean>;
    game_id: z.ZodNullable<z.ZodString>;
    outcomes: z.ZodNullable<z.ZodAny>;
    player_id: z.ZodNullable<z.ZodNumber>;
    promoted_at: z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
    unit_size: z.ZodNullable<z.ZodNumber>;
    promoted: z.ZodNullable<z.ZodBoolean>;
    ev_percent: z.ZodNullable<z.ZodNumber>;
    trend_score: z.ZodNullable<z.ZodNumber>;
    matchup_score: z.ZodNullable<z.ZodNumber>;
    line_score: z.ZodNullable<z.ZodNumber>;
    role_score: z.ZodNullable<z.ZodNumber>;
    is_promoted: z.ZodNullable<z.ZodBoolean>;
    updated_at: z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
    is_alt_line: z.ZodNullable<z.ZodBoolean>;
    is_primary: z.ZodNullable<z.ZodBoolean>;
    is_valid: z.ZodNullable<z.ZodBoolean>;
    over_odds: z.ZodNullable<z.ZodNumber>;
    under_odds: z.ZodNullable<z.ZodNumber>;
    game_time: z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
    id: z.ZodOptional<z.ZodString>;
    line: z.ZodNullable<z.ZodNumber>;
    odds: z.ZodNullable<z.ZodNumber>;
    game_date: z.ZodNullable<z.ZodString>;
    trend_confidence: z.ZodNullable<z.ZodNumber>;
    matchup_quality: z.ZodNullable<z.ZodNumber>;
    line_value_score: z.ZodNullable<z.ZodNumber>;
    role_stability: z.ZodNullable<z.ZodNumber>;
    confidence_score: z.ZodNullable<z.ZodNumber>;
    player_name: z.ZodNullable<z.ZodString>;
    sport: z.ZodNullable<z.ZodString>;
    team: z.ZodNullable<z.ZodString>;
    stat_type: z.ZodNullable<z.ZodString>;
    outcome: z.ZodNullable<z.ZodString>;
    direction: z.ZodNullable<z.ZodString>;
    player_slug: z.ZodNullable<z.ZodString>;
    external_game_id: z.ZodNullable<z.ZodString>;
    matchup: z.ZodNullable<z.ZodString>;
    sport_key: z.ZodNullable<z.ZodString>;
    fair_odds: z.ZodNullable<z.ZodString>;
    league: z.ZodNullable<z.ZodString>;
    unique_key: z.ZodNullable<z.ZodString>;
    start_time: z.ZodNullable<z.ZodString>;
    tier: z.ZodNullable<z.ZodString>;
    tier_tag: z.ZodNullable<z.ZodString>;
    event_id: z.ZodNullable<z.ZodString>;
    book: z.ZodNullable<z.ZodString>;
    provider: z.ZodNullable<z.ZodString>;
    source: z.ZodNullable<z.ZodString>;
    external_id: z.ZodNullable<z.ZodString>;
    market: z.ZodNullable<z.ZodString>;
    bet_type: z.ZodNullable<z.ZodString>;
    market_type: z.ZodNullable<z.ZodString>;
    opponent: z.ZodNullable<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    sport: string | null;
    market: string | null;
    book: string | null;
    tier: string | null;
    created_at: string | Date | null;
    line: number | null;
    game_id: string | null;
    player_id: number | null;
    stat_type: string | null;
    player_name: string | null;
    over_odds: number | null;
    under_odds: number | null;
    updated_at: string | Date | null;
    start_time: string | null;
    provider: string | null;
    team: string | null;
    matchup: string | null;
    source: string | null;
    odds: number | null;
    opponent: string | null;
    market_type: string | null;
    league: string | null;
    game_date: string | null;
    outcome: string | null;
    external_id: string | null;
    game_time: string | Date | null;
    scraped_at: string | Date | null;
    promoted: boolean | null;
    is_valid: boolean | null;
    external_game_id: string | null;
    sport_key: string | null;
    trend_confidence: number | null;
    matchup_quality: number | null;
    line_value_score: number | null;
    role_stability: number | null;
    confidence_score: number | null;
    edge_score: number | null;
    tier_tag: string | null;
    auto_approved: boolean | null;
    context_flag: boolean | null;
    promoted_to_picks: boolean | null;
    promoted_at: string | Date | null;
    is_promoted: boolean | null;
    bet_type: string | null;
    player_slug: string | null;
    fair_odds: string | null;
    unit_size: number | null;
    ev_percent: number | null;
    trend_score: number | null;
    matchup_score: number | null;
    line_score: number | null;
    role_score: number | null;
    direction: string | null;
    unique_key: string | null;
    event_id: string | null;
    is_alt_line: boolean | null;
    is_primary: boolean | null;
    id?: string | undefined;
    outcomes?: any;
}, {
    sport: string | null;
    market: string | null;
    book: string | null;
    tier: string | null;
    created_at: string | Date | null;
    line: number | null;
    game_id: string | null;
    player_id: number | null;
    stat_type: string | null;
    player_name: string | null;
    over_odds: number | null;
    under_odds: number | null;
    updated_at: string | Date | null;
    start_time: string | null;
    provider: string | null;
    team: string | null;
    matchup: string | null;
    source: string | null;
    odds: number | null;
    opponent: string | null;
    market_type: string | null;
    league: string | null;
    game_date: string | null;
    outcome: string | null;
    external_id: string | null;
    game_time: string | Date | null;
    scraped_at: string | Date | null;
    promoted: boolean | null;
    is_valid: boolean | null;
    external_game_id: string | null;
    sport_key: string | null;
    trend_confidence: number | null;
    matchup_quality: number | null;
    line_value_score: number | null;
    role_stability: number | null;
    confidence_score: number | null;
    edge_score: number | null;
    tier_tag: string | null;
    auto_approved: boolean | null;
    context_flag: boolean | null;
    promoted_to_picks: boolean | null;
    promoted_at: string | Date | null;
    is_promoted: boolean | null;
    bet_type: string | null;
    player_slug: string | null;
    fair_odds: string | null;
    unit_size: number | null;
    ev_percent: number | null;
    trend_score: number | null;
    matchup_score: number | null;
    line_score: number | null;
    role_score: number | null;
    direction: string | null;
    unique_key: string | null;
    event_id: string | null;
    is_alt_line: boolean | null;
    is_primary: boolean | null;
    id?: string | undefined;
    outcomes?: any;
}>;
export type RawProp = z.infer<typeof RawPropSchema>;
//# sourceMappingURL=ingestion.types.d.ts.map