"use strict";
// src/agents/IngestionAgent/ingestion.types.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.RawPropSchema = void 0;
const zod_1 = require("zod");
// Match your actual Supabase schema:
exports.RawPropSchema = zod_1.z.object({
    scraped_at: zod_1.z.string().or(zod_1.z.date()).nullable(), // timestamp with time zone
    edge_score: zod_1.z.number().int().nullable(),
    auto_approved: zod_1.z.boolean().nullable(),
    context_flag: zod_1.z.boolean().nullable(),
    created_at: zod_1.z.string().or(zod_1.z.date()).nullable(), // timestamp without time zone
    promoted_to_picks: zod_1.z.boolean().nullable(),
    game_id: zod_1.z.string().nullable(), // uuid (store as string for ingest)
    outcomes: zod_1.z.any().nullable(), // jsonb (parse as object/array)
    player_id: zod_1.z.number().int().nullable(),
    promoted_at: zod_1.z.string().or(zod_1.z.date()).nullable(),
    unit_size: zod_1.z.number().nullable(),
    promoted: zod_1.z.boolean().nullable(),
    ev_percent: zod_1.z.number().nullable(),
    trend_score: zod_1.z.number().int().nullable(),
    matchup_score: zod_1.z.number().int().nullable(),
    line_score: zod_1.z.number().int().nullable(),
    role_score: zod_1.z.number().int().nullable(),
    is_promoted: zod_1.z.boolean().nullable(),
    updated_at: zod_1.z.string().or(zod_1.z.date()).nullable(),
    is_alt_line: zod_1.z.boolean().nullable(),
    is_primary: zod_1.z.boolean().nullable(),
    is_valid: zod_1.z.boolean().nullable(),
    over_odds: zod_1.z.number().nullable(),
    under_odds: zod_1.z.number().nullable(),
    game_time: zod_1.z.string().or(zod_1.z.date()).nullable(), // timestamp with time zone
    id: zod_1.z.string().uuid().optional(), // uuid, generated by db
    line: zod_1.z.number().nullable(),
    odds: zod_1.z.number().int().nullable(),
    game_date: zod_1.z.string().nullable(), // date
    trend_confidence: zod_1.z.number().int().nullable(),
    matchup_quality: zod_1.z.number().int().nullable(),
    line_value_score: zod_1.z.number().int().nullable(),
    role_stability: zod_1.z.number().int().nullable(),
    confidence_score: zod_1.z.number().int().nullable(),
    player_name: zod_1.z.string().nullable(),
    sport: zod_1.z.string().nullable(),
    team: zod_1.z.string().nullable(),
    stat_type: zod_1.z.string().nullable(),
    outcome: zod_1.z.string().nullable(),
    direction: zod_1.z.string().nullable(),
    player_slug: zod_1.z.string().nullable(),
    external_game_id: zod_1.z.string().nullable(),
    matchup: zod_1.z.string().nullable(),
    sport_key: zod_1.z.string().nullable(),
    fair_odds: zod_1.z.string().nullable(),
    league: zod_1.z.string().nullable(),
    unique_key: zod_1.z.string().nullable(),
    start_time: zod_1.z.string().nullable(),
    tier: zod_1.z.string().nullable(),
    tier_tag: zod_1.z.string().nullable(),
    event_id: zod_1.z.string().nullable(),
    book: zod_1.z.string().nullable(),
    provider: zod_1.z.string().nullable(),
    source: zod_1.z.string().nullable(),
    external_id: zod_1.z.string().nullable(),
    market: zod_1.z.string().nullable(),
    bet_type: zod_1.z.string().nullable(),
    market_type: zod_1.z.string().nullable(),
    opponent: zod_1.z.string().nullable(),
});
