"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.schemas = exports.IngestionAgentConfigSchema = exports.DataProviderSchema = exports.RawPropSchema = void 0;
const z = __importStar(require("zod"));
const types_1 = require("../BaseAgent/types");
exports.RawPropSchema = z.object({
    // Core fields
    id: z.string().uuid().optional(), // uuid, generated by db
    player_name: z.string().nullable(),
    sport: z.string().nullable(),
    team: z.string().nullable(),
    stat_type: z.string().nullable(),
    outcome: z.string().nullable(),
    line: z.number().nullable(),
    odds: z.number().int().nullable(),
    game_date: z.string().nullable(), // date
    matchup: z.string().nullable(),
    // Scoring fields
    trend_confidence: z.number().int().nullable(),
    matchup_quality: z.number().int().nullable(),
    line_value_score: z.number().int().nullable(),
    role_stability: z.number().int().nullable(),
    confidence_score: z.number().int().nullable(),
    edge_score: z.number().int().nullable(),
    // Classification fields
    tier_tag: z.string().nullable(),
    auto_approved: z.boolean().nullable(),
    context_flag: z.boolean().nullable(),
    // Timestamps
    created_at: z.string().or(z.date()).nullable(), // timestamp without time zone
    scraped_at: z.string().or(z.date()).nullable(), // timestamp with time zone
    // Source fields
    source: z.string().nullable(),
    provider: z.string().nullable(),
    // Promotion fields
    promoted_to_picks: z.boolean().nullable(),
    promoted_at: z.string().or(z.date()).nullable(),
    promoted: z.boolean().nullable(),
    is_promoted: z.boolean().nullable(),
    // Game fields
    game_id: z.string().nullable(), // uuid (store as string for ingest)
    bet_type: z.string().nullable(),
    market_type: z.string().nullable(),
    outcomes: z.any().nullable(), // jsonb (parse as object/array)
    // Player fields
    player_id: z.number().int().nullable(),
    player_slug: z.string().nullable(),
    // External references
    external_game_id: z.string().nullable(),
    external_id: z.string().nullable(),
    // Sport fields
    sport_key: z.string().nullable(),
    league: z.string().nullable(),
    // Odds fields
    over_odds: z.number().nullable(),
    under_odds: z.number().nullable(),
    fair_odds: z.string().nullable(),
    market: z.string().nullable(),
    // Game timing
    game_time: z.string().or(z.date()).nullable(), // timestamp with time zone
    start_time: z.string().or(z.date()).nullable(),
    // Team fields
    home_team: z.string().nullable(),
    home_team_id: z.number().int().nullable(),
    away_team: z.string().nullable(),
    away_team_id: z.number().int().nullable(),
    opponent: z.string().nullable(),
    // Additional fields
    unit_size: z.number().nullable(),
    tier: z.string().nullable(),
    ev_percent: z.number().nullable(),
    trend_score: z.number().int().nullable(),
    matchup_score: z.number().int().nullable(),
    line_score: z.number().int().nullable(),
    role_score: z.number().int().nullable(),
    direction: z.string().nullable(),
    unique_key: z.string().nullable(),
    event_id: z.string().nullable(),
    book: z.string().nullable(),
    updated_at: z.string().or(z.date()).nullable(),
    is_alt_line: z.boolean().nullable(),
    is_primary: z.boolean().nullable(),
    is_valid: z.boolean().nullable(),
});
// Data provider configuration
exports.DataProviderSchema = z.object({
    name: z.string(),
    enabled: z.boolean().default(true),
    url: z.string().url(),
    apiKey: z.string().optional(),
    headers: z.record(z.string(), z.string()).optional(),
    timeout: z.number().default(30000),
    retryAttempts: z.number().default(3),
    retryDelay: z.number().default(1000),
    rateLimit: z.object({
        requests: z.number().default(100),
        window: z.number().default(60000), // 1 minute
    }).optional(),
});
// IngestionAgent specific configuration
exports.IngestionAgentConfigSchema = z.object({
    providers: z.array(exports.DataProviderSchema),
    batchSize: z.number().min(1).max(1000).default(100),
    processingTimeout: z.number().default(300000), // 5 minutes
    duplicateCheckEnabled: z.boolean().default(true),
    duplicateCheckWindow: z.number().default(86400000), // 24 hours in ms
    validationEnabled: z.boolean().default(true),
    normalizationEnabled: z.boolean().default(true)
}).merge(types_1.BaseAgentConfigSchema);
// Export schemas for validation
exports.schemas = {
    RawProp: exports.RawPropSchema,
    DataProvider: exports.DataProviderSchema,
    IngestionAgentConfig: exports.IngestionAgentConfigSchema
};
