global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/recording_rules.yml"
  - "rules/alerting_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: 'grading_agent'
    static_configs:
      - targets: ['localhost:9002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'grading_agent_${1}'

  - job_name: 'data_agent'
    static_configs:
      - targets: ['localhost:9003']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'data_agent_${1}'

  - job_name: 'contest_agent'
    static_configs:
      - targets: ['localhost:9004']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'contest_agent_${1}'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s 