import { BaseAgent } from '../BaseAgent';
import { BaseAgentConfig, BaseAgentDependencies, BaseMetrics } from '../BaseAgent/types';
export declare class RiskManagementAgent extends BaseAgent {
    private portfolioOptimizer;
    private riskAnalyzer;
    private positionSizer;
    private hedgeEngine;
    private parlayHedgeCalculator;
    private riskMetrics;
    private portfolioRisks;
    private globalRiskLimits;
    constructor(config: BaseAgentConfig, deps: BaseAgentDependencies);
    protected initialize(): Promise<void>;
    protected process(): Promise<void>;
    private analyzePortfolioRisks;
    private checkRiskLimitViolations;
    private optimizePositionSizes;
    private generateHedgeRecommendations;
    private analyzeParlayHedgeOpportunities;
    private monitorCorrelationChanges;
    private generateRiskInsights;
    private analyzeUserPortfolio;
    private identifyRiskViolations;
    private handleRiskViolations;
    private applyPositionOptimizations;
    private processHedgeRecommendations;
    private handleSignificantCorrelationChange;
    private getActiveUsersWithPositions;
    private getUserPositions;
    private getUserBankroll;
    private getUserRiskLimits;
    private calculateDiversificationRatio;
    private generateImmediateRiskAlert;
    private sendCriticalRiskAlert;
    private sendHedgeRecommendation;
    private sendParlayHedgeAlert;
    private getActiveParlayBets;
    private notifyCorrelationChange;
    private processPositionChange;
    private analyzeRiskDistribution;
    private generateCorrelationInsights;
    private analyzePortfolioPerformance;
    private calculateRiskAdjustedReturns;
    private generateSystemRecommendations;
    private loadPortfolioRisks;
    private loadRiskLimitsConfiguration;
    protected cleanup(): Promise<void>;
    protected collectMetrics(): Promise<BaseMetrics>;
    checkHealth(): Promise<any>;
}
//# sourceMappingURL=index.d.ts.map