export const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
export const NEXT_PUBLIC_SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

// Environment configuration object
export const env = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  CAPPER_ID: process.env.CAPPER_ID,
  DEFAULT_CAPPER_ID: process.env.DEFAULT_CAPPER_ID,
  TEST_CAPPER_ID: process.env.TEST_CAPPER_ID,
  SMARTFORM_DEFAULT_CAPPER_ID: process.env.SMARTFORM_DEFAULT_CAPPER_ID,
  CAPPER_IDS: process.env.CAPPER_IDS,
  TENANT_ID: process.env.TENANT_ID,
  PICK_DRIVER: process.env.PICK_DRIVER,
  PUBLISH_MODE: process.env.PUBLISH_MODE,
  CDN_BASE: process.env.CDN_BASE,
};
