/**
 * scoringFixtures.ts — Deterministic test fixtures for scoring V2
 *
 * 20 fixtures covering the full spectrum of scoring scenarios:
 * - S/A/B/C/D tier distribution
 * - Favorites and underdogs
 * - Missing data (fallback testing)
 * - Sport-specific (NBA, NFL, MLB, NHL)
 * - Edge cases
 *
 * Created: 2026-01-29 (Tranche 3, Stage 4 — Scoring Rebuild)
 */

import type { GradingFeatureSet } from '../../../../types/GradingFeatureSet';

export interface ScoringFixture {
  name: string;
  description: string;
  input: Partial<GradingFeatureSet>;
  expected: {
    tierRange: string[];
    scoreMin: number;
    scoreMax: number;
    evSign: 'positive' | 'negative' | 'zero' | 'any';
  };
}

/** Shared defaults for all fixtures to satisfy required GradingFeatureSet fields */
const BASE: Omit<
  GradingFeatureSet,
  | 'expectedValue'
  | 'lineMovement'
  | 'matchupRating'
  | 'playerForm'
  | 'injuryImpact'
  | 'weatherImpact'
  | 'marketIntelligence'
  | 'sharpMoney'
  | 'volumeProfile'
  | 'closingLineValue'
  | 'playerFatigue'
  | 'venueAdvantage'
  | 'refereeImpact'
  | 'paceImpact'
  | 'motivationalFactors'
  | 'correlationRisk'
  | 'volatility'
  | 'portfolioImpact'
> = {
  propId: 'fixture',
  date: '2026-01-29',
  sport: 'NBA',
  league: 'NBA',
  player: 'Test Player',
  odds: -110,
  market: { type: 'points', odds: -110, line: 22.5 },
  dataQuality: {
    dataValidationScore: 0.95,
    outlierScore: 0.95,
    consistencyScore: 0.95,
    completeness: 0.9,
  },
  timestamp: '2026-01-29T12:00:00Z',
  version: 'fixture-v1',
  source: 'test',
  confidence: 0.8,
};

export const SCORING_FIXTURES: ScoringFixture[] = [
  // ── Tier Distribution (5) ─────────────────────────────────────────────────

  {
    name: 'S-tier: Elite pick',
    description: 'Strong EV, sharp money, high matchup — should score S-tier',
    input: {
      ...BASE,
      propId: 'fix-s-tier',
      expectedValue: 25,
      lineMovement: 3,
      matchupRating: 90,
      playerForm: 92,
      injuryImpact: 8,
      weatherImpact: 0,
      marketIntelligence: 85,
      sharpMoney: 85,
      volumeProfile: 75,
      closingLineValue: 8,
      playerFatigue: 80,
      venueAdvantage: 15,
      refereeImpact: 5,
      paceImpact: 14,
      motivationalFactors: 20,
      correlationRisk: 0.1,
      volatility: 2,
      portfolioImpact: 0.05,
    },
    expected: { tierRange: ['S'], scoreMin: 70, scoreMax: 100, evSign: 'positive' },
  },
  {
    name: 'A-tier: Good pick',
    description: 'Positive EV, decent signals — should score A-tier',
    input: {
      ...BASE,
      propId: 'fix-a-tier',
      expectedValue: 10,
      lineMovement: 2,
      matchupRating: 70,
      playerForm: 72,
      injuryImpact: 4,
      weatherImpact: 0,
      marketIntelligence: 65,
      sharpMoney: 65,
      volumeProfile: 60,
      closingLineValue: 3,
      playerFatigue: 65,
      venueAdvantage: 12,
      refereeImpact: 2,
      paceImpact: 11,
      motivationalFactors: 15,
      correlationRisk: 0.2,
      volatility: 4,
      portfolioImpact: 0.15,
    },
    expected: { tierRange: ['A', 'B'], scoreMin: 45, scoreMax: 75, evSign: 'positive' },
  },
  {
    name: 'B-tier: Average pick',
    description: 'Neutral EV, mixed signals — should score B-tier',
    input: {
      ...BASE,
      propId: 'fix-b-tier',
      expectedValue: 2,
      lineMovement: 1,
      matchupRating: 55,
      playerForm: 55,
      injuryImpact: 2,
      weatherImpact: 0,
      marketIntelligence: 50,
      sharpMoney: 50,
      volumeProfile: 50,
      closingLineValue: 0,
      playerFatigue: 55,
      venueAdvantage: 10,
      refereeImpact: 0,
      paceImpact: 10,
      motivationalFactors: 15,
      correlationRisk: 0.3,
      volatility: 5,
      portfolioImpact: 0.2,
    },
    expected: { tierRange: ['B', 'C'], scoreMin: 35, scoreMax: 55, evSign: 'positive' },
  },
  {
    name: 'C-tier: Below average pick',
    description: 'Slight negative EV, weak signals — should score C-tier',
    input: {
      ...BASE,
      propId: 'fix-c-tier',
      expectedValue: -5,
      lineMovement: 0,
      matchupRating: 35,
      playerForm: 38,
      injuryImpact: 1,
      weatherImpact: 0,
      marketIntelligence: 35,
      sharpMoney: 35,
      volumeProfile: 40,
      closingLineValue: -2,
      playerFatigue: 40,
      venueAdvantage: 5,
      refereeImpact: -3,
      paceImpact: 8,
      motivationalFactors: 8,
      correlationRisk: 0.4,
      volatility: 6,
      portfolioImpact: 0.3,
    },
    expected: { tierRange: ['C', 'D'], scoreMin: 20, scoreMax: 45, evSign: 'negative' },
  },
  {
    name: 'D-tier: Poor pick',
    description: 'Negative EV, bad signals — should score D-tier',
    input: {
      ...BASE,
      propId: 'fix-d-tier',
      expectedValue: -20,
      lineMovement: 0,
      matchupRating: 20,
      playerForm: 18,
      injuryImpact: 0,
      weatherImpact: 0,
      marketIntelligence: 20,
      sharpMoney: 20,
      volumeProfile: 25,
      closingLineValue: -8,
      playerFatigue: 20,
      venueAdvantage: 2,
      refereeImpact: -5,
      paceImpact: 5,
      motivationalFactors: 3,
      correlationRisk: 0.7,
      volatility: 8,
      portfolioImpact: 0.6,
    },
    expected: { tierRange: ['D'], scoreMin: 0, scoreMax: 35, evSign: 'negative' },
  },

  // ── Favorites & Underdogs (2) ─────────────────────────────────────────────

  {
    name: 'Heavy favorite (-200)',
    description: 'Props with heavy favorite odds (-200)',
    input: {
      ...BASE,
      propId: 'fix-fav-200',
      odds: -200,
      market: { type: 'points', odds: -200, line: 25.5 },
      expectedValue: -4,
      lineMovement: 1,
      matchupRating: 60,
      playerForm: 65,
      injuryImpact: 3,
      weatherImpact: 0,
      marketIntelligence: 55,
      sharpMoney: 55,
      volumeProfile: 50,
      closingLineValue: 1,
      playerFatigue: 60,
      venueAdvantage: 10,
      refereeImpact: 0,
      paceImpact: 10,
      motivationalFactors: 15,
      correlationRisk: 0.25,
      volatility: 4,
      portfolioImpact: 0.1,
    },
    expected: { tierRange: ['B', 'C', 'D'], scoreMin: 25, scoreMax: 55, evSign: 'negative' },
  },
  {
    name: 'Underdog (+200)',
    description: 'Props with underdog odds (+200)',
    input: {
      ...BASE,
      propId: 'fix-dog-200',
      odds: 200,
      market: { type: 'points', odds: 200, line: 30.5 },
      expectedValue: 15,
      lineMovement: 2,
      matchupRating: 55,
      playerForm: 60,
      injuryImpact: 5,
      weatherImpact: 0,
      marketIntelligence: 60,
      sharpMoney: 60,
      volumeProfile: 45,
      closingLineValue: 4,
      playerFatigue: 65,
      venueAdvantage: 8,
      refereeImpact: 1,
      paceImpact: 12,
      motivationalFactors: 18,
      correlationRisk: 0.15,
      volatility: 6,
      portfolioImpact: 0.08,
    },
    expected: { tierRange: ['A', 'B'], scoreMin: 45, scoreMax: 70, evSign: 'positive' },
  },

  // ── Missing Data (3) ─────────────────────────────────────────────────────

  {
    name: 'Missing win_prob (fallback to devig)',
    description: 'No projected_win_prob — EV should derive from market odds',
    input: {
      ...BASE,
      propId: 'fix-no-winprob',
      expectedValue: 5,
      lineMovement: 1,
      matchupRating: 60,
      playerForm: 60,
      injuryImpact: 2,
      weatherImpact: 0,
      marketIntelligence: 55,
      sharpMoney: 55,
      volumeProfile: 50,
      closingLineValue: 2,
      playerFatigue: 55,
      venueAdvantage: 10,
      refereeImpact: 0,
      paceImpact: 10,
      motivationalFactors: 12,
      correlationRisk: 0.2,
      volatility: 5,
      portfolioImpact: 0.1,
    },
    expected: { tierRange: ['B', 'C', 'A'], scoreMin: 35, scoreMax: 65, evSign: 'positive' },
  },
  {
    name: 'Missing opposing side odds',
    description: 'Only over_odds, no under_odds — single-side implied prob',
    input: {
      ...BASE,
      propId: 'fix-no-under',
      expectedValue: 3,
      lineMovement: 0,
      matchupRating: 50,
      playerForm: 50,
      injuryImpact: 0,
      weatherImpact: 0,
      marketIntelligence: 50,
      sharpMoney: 50,
      volumeProfile: 50,
      closingLineValue: 0,
      playerFatigue: 50,
      venueAdvantage: 10,
      refereeImpact: 0,
      paceImpact: 10,
      motivationalFactors: 15,
      correlationRisk: 0.2,
      volatility: 5,
      portfolioImpact: 0.1,
    },
    expected: { tierRange: ['B', 'C'], scoreMin: 35, scoreMax: 55, evSign: 'positive' },
  },
  {
    name: 'All-neutral fallback',
    description: 'Every optional field missing — all registry fallbacks used',
    input: {
      propId: 'fix-all-neutral',
      date: '2026-01-29',
      sport: 'NBA',
      league: 'NBA',
      market: { type: 'points', odds: -110, line: 22.5 },
      dataQuality: {
        dataValidationScore: 0.95,
        outlierScore: 0.95,
        consistencyScore: 0.95,
        completeness: 0.5,
      },
      timestamp: '2026-01-29T12:00:00Z',
      version: 'fixture-v1',
      source: 'test',
      confidence: 0.5,
    } as any,
    expected: { tierRange: ['B', 'C', 'D'], scoreMin: 20, scoreMax: 55, evSign: 'any' },
  },

  // ── Sport-Specific (4) ────────────────────────────────────────────────────

  {
    name: 'MLB weather-heavy',
    description: 'MLB game with significant weather impact (outdoor)',
    input: {
      ...BASE,
      propId: 'fix-mlb-weather',
      sport: 'MLB',
      league: 'MLB',
      expectedValue: 8,
      lineMovement: 1.5,
      matchupRating: 65,
      playerForm: 70,
      injuryImpact: 3,
      weatherImpact: 7,
      marketIntelligence: 60,
      sharpMoney: 60,
      volumeProfile: 55,
      closingLineValue: 2,
      playerFatigue: 60,
      venueAdvantage: 12,
      refereeImpact: 1,
      paceImpact: 8,
      motivationalFactors: 14,
      correlationRisk: 0.2,
      volatility: 5,
      portfolioImpact: 0.1,
    },
    expected: { tierRange: ['A', 'B'], scoreMin: 40, scoreMax: 70, evSign: 'positive' },
  },
  {
    name: 'NFL injury-heavy',
    description: 'NFL game where injuries are the dominant factor',
    input: {
      ...BASE,
      propId: 'fix-nfl-injury',
      sport: 'NFL',
      league: 'NFL',
      expectedValue: 12,
      lineMovement: 3,
      matchupRating: 75,
      playerForm: 68,
      injuryImpact: 9,
      weatherImpact: 3,
      marketIntelligence: 70,
      sharpMoney: 72,
      volumeProfile: 60,
      closingLineValue: 4,
      playerFatigue: 70,
      venueAdvantage: 14,
      refereeImpact: 3,
      paceImpact: 10,
      motivationalFactors: 22,
      correlationRisk: 0.15,
      volatility: 3,
      portfolioImpact: 0.08,
    },
    expected: { tierRange: ['A', 'S'], scoreMin: 55, scoreMax: 85, evSign: 'positive' },
  },
  {
    name: 'NBA pace-dominant',
    description: 'NBA game where pace is the biggest factor',
    input: {
      ...BASE,
      propId: 'fix-nba-pace',
      sport: 'NBA',
      league: 'NBA',
      expectedValue: 6,
      lineMovement: 1,
      matchupRating: 60,
      playerForm: 62,
      injuryImpact: 2,
      weatherImpact: 0,
      marketIntelligence: 58,
      sharpMoney: 55,
      volumeProfile: 50,
      closingLineValue: 1,
      playerFatigue: 60,
      venueAdvantage: 10,
      refereeImpact: 2,
      paceImpact: 18,
      motivationalFactors: 12,
      correlationRisk: 0.2,
      volatility: 4,
      portfolioImpact: 0.1,
    },
    expected: { tierRange: ['A', 'B'], scoreMin: 45, scoreMax: 65, evSign: 'positive' },
  },
  {
    name: 'NHL full-feature',
    description: 'NHL game with all features populated',
    input: {
      ...BASE,
      propId: 'fix-nhl-full',
      sport: 'NHL',
      league: 'NHL',
      expectedValue: 7,
      lineMovement: 2,
      matchupRating: 62,
      playerForm: 66,
      injuryImpact: 4,
      weatherImpact: 0,
      marketIntelligence: 60,
      sharpMoney: 62,
      volumeProfile: 55,
      closingLineValue: 3,
      playerFatigue: 65,
      venueAdvantage: 11,
      refereeImpact: 1,
      paceImpact: 12,
      motivationalFactors: 16,
      correlationRisk: 0.18,
      volatility: 4,
      portfolioImpact: 0.1,
    },
    expected: { tierRange: ['A', 'B'], scoreMin: 45, scoreMax: 70, evSign: 'positive' },
  },

  // ── Edge Cases (4) ────────────────────────────────────────────────────────

  {
    name: 'Score floor (all zeros)',
    description: 'Minimum possible values — score should floor near 0',
    input: {
      ...BASE,
      propId: 'fix-floor',
      expectedValue: -50,
      lineMovement: 0,
      matchupRating: 0,
      playerForm: 0,
      injuryImpact: 0,
      weatherImpact: 0,
      marketIntelligence: 0,
      sharpMoney: 0,
      volumeProfile: 0,
      closingLineValue: -20,
      playerFatigue: 0,
      venueAdvantage: 0,
      refereeImpact: -10,
      paceImpact: 0,
      motivationalFactors: 0,
      correlationRisk: 1.0,
      volatility: 10,
      portfolioImpact: 1.0,
    },
    expected: { tierRange: ['D'], scoreMin: 0, scoreMax: 15, evSign: 'negative' },
  },
  {
    name: 'Score ceiling (all max)',
    description: 'Maximum possible values — score should hit ceiling near 100',
    input: {
      ...BASE,
      propId: 'fix-ceiling',
      expectedValue: 50,
      lineMovement: 10,
      matchupRating: 100,
      playerForm: 100,
      injuryImpact: 10,
      weatherImpact: 10,
      marketIntelligence: 100,
      sharpMoney: 100,
      volumeProfile: 100,
      closingLineValue: 20,
      playerFatigue: 100,
      venueAdvantage: 20,
      refereeImpact: 10,
      paceImpact: 20,
      motivationalFactors: 30,
      correlationRisk: 0,
      volatility: 0,
      portfolioImpact: 0,
    },
    expected: { tierRange: ['S'], scoreMin: 90, scoreMax: 100, evSign: 'positive' },
  },
  {
    name: 'Negative EV with strong signals',
    description: 'Negative EV but other signals are strong — tests EV weight',
    input: {
      ...BASE,
      propId: 'fix-neg-ev-strong',
      expectedValue: -15,
      lineMovement: 4,
      matchupRating: 80,
      playerForm: 85,
      injuryImpact: 7,
      weatherImpact: 0,
      marketIntelligence: 75,
      sharpMoney: 75,
      volumeProfile: 70,
      closingLineValue: 5,
      playerFatigue: 75,
      venueAdvantage: 14,
      refereeImpact: 4,
      paceImpact: 14,
      motivationalFactors: 20,
      correlationRisk: 0.1,
      volatility: 3,
      portfolioImpact: 0.05,
    },
    expected: { tierRange: ['A', 'B', 'S'], scoreMin: 45, scoreMax: 80, evSign: 'negative' },
  },
  {
    name: 'Zero odds edge case',
    description: 'Odds set to 0 — should not crash, use fallbacks',
    input: {
      ...BASE,
      propId: 'fix-zero-odds',
      odds: 0,
      market: { type: 'points', odds: 0, line: 22.5 },
      expectedValue: 0,
      lineMovement: 0,
      matchupRating: 50,
      playerForm: 50,
      injuryImpact: 0,
      weatherImpact: 0,
      marketIntelligence: 50,
      sharpMoney: 50,
      volumeProfile: 50,
      closingLineValue: 0,
      playerFatigue: 50,
      venueAdvantage: 10,
      refereeImpact: 0,
      paceImpact: 10,
      motivationalFactors: 15,
      correlationRisk: 0.2,
      volatility: 5,
      portfolioImpact: 0.1,
    },
    expected: { tierRange: ['B', 'C', 'D'], scoreMin: 25, scoreMax: 55, evSign: 'zero' },
  },

  // ── Professional Capper Data Fixtures (2) ─────────────────────────────────

  {
    name: 'With steam move data',
    description: 'Steam move detected — capper features should activate',
    input: {
      ...BASE,
      propId: 'fix-steam',
      expectedValue: 8,
      lineMovement: 3,
      matchupRating: 65,
      playerForm: 68,
      injuryImpact: 3,
      weatherImpact: 0,
      marketIntelligence: 65,
      sharpMoney: 70,
      volumeProfile: 60,
      closingLineValue: 3,
      playerFatigue: 65,
      venueAdvantage: 11,
      refereeImpact: 2,
      paceImpact: 12,
      motivationalFactors: 14,
      correlationRisk: 0.15,
      volatility: 4,
      portfolioImpact: 0.1,
      steamMoveData: { detected: true, confidence: 0.85, timestamp: Date.now() },
      hoursToGame: 18,
    },
    expected: { tierRange: ['A', 'B'], scoreMin: 50, scoreMax: 75, evSign: 'positive' },
  },
  {
    name: 'With betting percentages',
    description: 'Public vs sharp split data available — contrarian detection',
    input: {
      ...BASE,
      propId: 'fix-contrarian',
      expectedValue: 6,
      lineMovement: 1,
      matchupRating: 58,
      playerForm: 60,
      injuryImpact: 2,
      weatherImpact: 0,
      marketIntelligence: 55,
      sharpMoney: 65,
      volumeProfile: 50,
      closingLineValue: 2,
      playerFatigue: 60,
      venueAdvantage: 10,
      refereeImpact: 1,
      paceImpact: 11,
      motivationalFactors: 13,
      correlationRisk: 0.2,
      volatility: 4,
      portfolioImpact: 0.1,
      bettingPercentages: { public: 75, sharp: 25, timestamp: Date.now() },
      hoursToGame: 24,
    },
    expected: { tierRange: ['A', 'B'], scoreMin: 45, scoreMax: 70, evSign: 'positive' },
  },
];
