import { z } from 'zod';
declare const EnvironmentSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<{
        production: "production";
        development: "development";
        staging: "staging";
    }>>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<{
        error: "error";
        warn: "warn";
        info: "info";
        debug: "debug";
    }>>;
    DEBUG_MODE: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    API_PORT: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    DISCORD_BOT_PORT: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    DASHBOARD_PORT: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    SMART_FORM_PORT: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    COMMAND_CENTER_PORT: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    SUPABASE_URL: z.ZodString;
    SUPABASE_ANON_KEY: z.ZodString;
    SUPABASE_SERVICE_ROLE_KEY: z.ZodString;
    NEXT_PUBLIC_SUPABASE_URL: z.ZodString;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.ZodString;
    OPTIMAL_API_KEY: z.ZodString;
    ODDS_API_KEY: z.ZodString;
    DISCORD_BOT_TOKEN: z.ZodString;
    DISCORD_TOKEN: z.ZodString;
    DISCORD_CLIENT_ID: z.ZodString;
    DISCORD_GUILD_ID: z.ZodString;
    ADMIN_ROLE_IDS: z.ZodDefault<z.ZodString>;
    MODERATOR_ROLE_IDS: z.ZodDefault<z.ZodString>;
    BOT_ROLE_IDS: z.ZodDefault<z.ZodString>;
    STAFF_ROLE_IDS: z.ZodDefault<z.ZodString>;
    OWNER_ROLE_IDS: z.ZodDefault<z.ZodString>;
    VIP_ROLE_IDS: z.ZodDefault<z.ZodString>;
    VIP_PLUS_ROLE_IDS: z.ZodDefault<z.ZodString>;
    CAPPER_ROLE_IDS: z.ZodDefault<z.ZodString>;
    TRIAL_ROLE_IDS: z.ZodDefault<z.ZodString>;
    ANNOUNCEMENTS_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    GENERAL_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    WELCOME_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    FREE_PICKS_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    VIP_PICKS_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    VIP_PLUS_PICKS_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    VIP_GENERAL_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    VIP_STRATEGY_ROOM_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    VIP_PLUS_GENERAL_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    VIP_PLUS_STRATEGY_ROOM_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    VIP_PLUS_EXCLUSIVE_INSIGHTS_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    VIP_PLUS_TRADER_INSIGHTS_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    SUPPORT_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    THREADS_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    SPORTS_TALK_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    ADMIN_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    BOT_LOGS_CHANNEL_ID: z.ZodDefault<z.ZodString>;
    TEMPORAL_ADDRESS: z.ZodDefault<z.ZodString>;
    TEMPORAL_SERVER_URL: z.ZodDefault<z.ZodString>;
    TEMPORAL_NAMESPACE: z.ZodDefault<z.ZodString>;
    TEMPORAL_TASK_QUEUE: z.ZodDefault<z.ZodString>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    CACHE_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    JWT_SECRET: z.ZodString;
    ENCRYPTION_KEY: z.ZodString;
    NEXTAUTH_SECRET: z.ZodString;
    NEXT_PUBLIC_APP_URL: z.ZodString;
    NEXTAUTH_URL: z.ZodString;
    NEXT_PUBLIC_PLATFORM_API_URL: z.ZodString;
    UNIT_TALK_PRODUCTION_URL: z.ZodString;
    NEXT_PUBLIC_ANALYTICS_API_URL: z.ZodString;
    AGENTS_BASE_URL: z.ZodString;
    AGENTS_API_KEY: z.ZodString;
    SYNC_API_KEY: z.ZodString;
    AUTO_GRADING_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    DM_NOTIFICATIONS_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    ANALYTICS_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    THREAD_MANAGEMENT_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    CAPPER_TRACKING_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    FORUM_MANAGEMENT_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    CAPPER_THREAD_AUTO_CREATE: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    CAPPER_QA_THREADS_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    CAPPER_PERFORMANCE_TRACKING: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    CAPPER_DAILY_PICK_AGGREGATION: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    XP_SYSTEM_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    LEADERBOARD_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    ENGAGEMENT_TRACKING_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    MILESTONE_CELEBRATIONS_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    STREAK_TRACKING_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    ACHIEVEMENT_SYSTEM_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    VIP_CONVERSION_TRACKING: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    TRIAL_USAGE_TRACKING: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    UPGRADE_FUNNEL_ANALYTICS: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    AUTO_VIP_PROMOTION_MESSAGES: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    WELCOME_SYSTEM_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    NEW_MEMBER_GUIDE_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    AUTO_ROLE_SUGGESTIONS: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    XP_MULTIPLIER_GENERAL: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    XP_MULTIPLIER_VIP: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    XP_MULTIPLIER_VIP_PLUS: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    XP_GENERAL_CHANNELS: z.ZodDefault<z.ZodString>;
    XP_VIP_CHANNELS: z.ZodDefault<z.ZodString>;
    XP_VIP_PLUS_CHANNELS: z.ZodDefault<z.ZodString>;
    MAX_PICKS_PER_DAY: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    MAX_UNITS_PER_PICK: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    MIN_UNITS_PER_PICK: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    PICK_CATEGORIES: z.ZodDefault<z.ZodString>;
    AUTO_GRADE_DELAY_HOURS: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    GRADE_CONFIRMATION_REQUIRED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    MANUAL_GRADE_OVERRIDE: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    RATE_LIMIT_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    AUTO_BACKUP_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    HOT_RELOAD: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    SECURITY_HEADERS_ENABLED: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
    THREAD_AUTO_ARCHIVE_MINUTES: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    FORUM_AUTO_CLEANUP_DAYS: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    CAPPER_THREAD_AUTO_ARCHIVE_HOURS: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    DATA_RETENTION_DAYS: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    BACKUP_FREQUENCY_HOURS: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    MAX_DMS_PER_HOUR: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    MAX_THREADS_PER_DAY: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<number, string>>;
    NOTION_TOKEN: z.ZodOptional<z.ZodString>;
    DISCORD_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    ALERTS_CHANNEL_ID: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
declare class EnvironmentConfig {
    private config;
    private isValidated;
    constructor();
    private loadConfiguration;
    private getBrowserConfig;
    get all(): Readonly<z.infer<typeof EnvironmentSchema>>;
    get database(): {
        supabaseUrl: string;
        supabaseAnonKey: string;
        supabaseServiceRoleKey: string;
        publicSupabaseUrl: string;
        publicSupabaseAnonKey: string;
    };
    get apiKeys(): {
        optimal: string;
        odds: string;
        agents: string;
        sync: string;
    };
    get discord(): {
        botToken: string;
        token: string;
        clientId: string;
        guildId: string;
        roles: {
            admin: string[];
            moderator: string[];
            bot: string[];
            staff: string[];
            owner: string[];
            vip: string[];
            vipPlus: string[];
            capper: string[];
            trial: string[];
        };
        channels: {
            announcements: string;
            general: string;
            welcome: string;
            freePicks: string;
            vipPicks: string;
            vipPlusPicks: string;
            vipGeneral: string;
            vipStrategyRoom: string;
            vipPlusGeneral: string;
            vipPlusStrategyRoom: string;
            vipPlusExclusiveInsights: string;
            vipPlusTraderInsights: string;
            support: string;
            threads: string;
            sportsTalk: string;
            admin: string;
            botLogs: string;
        };
    };
    get urls(): {
        app: string;
        platformApi: string;
        production: string;
        analytics: string;
        agents: string;
        nextAuth: string;
    };
    get security(): {
        jwtSecret: string;
        encryptionKey: string;
        nextAuthSecret: string;
    };
    get temporal(): {
        address: string;
        serverUrl: string;
        namespace: string;
        taskQueue: string;
    };
    get features(): {
        autoGradingEnabled: boolean;
        dmNotificationsEnabled: boolean;
        analyticsEnabled: boolean;
        threadManagementEnabled: boolean;
        capperTrackingEnabled: boolean;
        forumManagementEnabled: boolean;
        capperThreadAutoCreate: boolean;
        capperQaThreadsEnabled: boolean;
        capperPerformanceTracking: boolean;
        capperDailyPickAggregation: boolean;
        xpSystemEnabled: boolean;
        leaderboardEnabled: boolean;
        engagementTrackingEnabled: boolean;
        milestoneCelebrationsEnabled: boolean;
        streakTrackingEnabled: boolean;
        achievementSystemEnabled: boolean;
        vipConversionTracking: boolean;
        trialUsageTracking: boolean;
        upgradeFunnelAnalytics: boolean;
        autoVipPromotionMessages: boolean;
        welcomeSystemEnabled: boolean;
        newMemberGuideEnabled: boolean;
        autoRoleSuggestions: boolean;
    };
    get xpSystem(): {
        multipliers: {
            general: number;
            vip: number;
            vipPlus: number;
        };
        channels: {
            general: string[];
            vip: string[];
            vipPlus: string[];
        };
    };
    get pickManagement(): {
        limits: {
            maxPicksPerDay: number;
            maxUnitsPerPick: number;
            minUnitsPerPick: number;
        };
        categories: string[];
        grading: {
            autoGradeDelayHours: number;
            gradeConfirmationRequired: boolean;
            manualGradeOverride: boolean;
        };
    };
    get performance(): {
        rateLimitEnabled: boolean;
        autoBackupEnabled: boolean;
        hotReload: boolean;
        securityHeadersEnabled: boolean;
        cacheEnabled: boolean;
        redis: {
            url: string;
        };
        limits: {
            threadAutoArchiveMinutes: number;
            forumAutoCleanupDays: number;
            capperThreadAutoArchiveHours: number;
            dataRetentionDays: number;
            backupFrequencyHours: number;
            maxDmsPerHour: number;
            maxThreadsPerDay: number;
        };
    };
    get ports(): {
        api: number;
        discordBot: number;
        dashboard: number;
        smartForm: number;
        commandCenter: number;
    };
    get isProduction(): boolean;
    get isDevelopment(): boolean;
    get isStaging(): boolean;
    get environment(): string;
    get logLevel(): string;
    get debugMode(): boolean;
}
export declare const env: EnvironmentConfig;
export default env;
export type EnvironmentConfiguration = z.infer<typeof EnvironmentSchema>;
export declare function validateProductionApiKeys(): void;
export declare function getEnvironmentOverrides(environment: string): Record<string, any>;
//# sourceMappingURL=environment.d.ts.map