export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      cappers: {
        Row: {
          id: string;
          name: string;
          username?: string;
          discord_id?: string;
          tier?: string;
          capper_tier?: string;
          active: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          name: string;
          username?: string;
          discord_id?: string;
          tier?: string;
          capper_tier?: string;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          username?: string;
          discord_id?: string;
          tier?: string;
          capper_tier?: string;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      teams: {
        Row: {
          id: string;
          name: string;
          sport: string;
          abbreviation: string;
          active: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          name: string;
          sport: string;
          abbreviation: string;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          sport?: string;
          abbreviation?: string;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      players: {
        Row: {
          id: string;
          name: string;
          team_id: string;
          sport: string;
          position: string;
          active: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          name: string;
          team_id: string;
          sport: string;
          position: string;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          team_id?: string;
          sport?: string;
          position?: string;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      games: {
        Row: {
          id: string;
          sport: string;
          league?: string;
          home_team_id: string;
          away_team_id: string;
          home_team?: string;
          away_team?: string;
          game_date: string;
          game_time: string;
          commence_time?: string;
          start_time?: string;
          status: string;
          spread?: string;
          total?: string;
          moneyline_home?: string;
          moneyline_away?: string;
          spread_odds?: string;
          total_over_odds?: string;
          total_under_odds?: string;
          matchup?: string;
          away_team_meta?: Json;
          home_team_meta?: Json;
          home_odds?: number;
          away_odds?: number;
          home_spread?: number;
          away_spread?: number;
          home_spread_odds?: number;
          away_spread_odds?: number;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          sport: string;
          league?: string;
          home_team_id: string;
          away_team_id: string;
          home_team?: string;
          away_team?: string;
          game_date: string;
          game_time: string;
          commence_time?: string;
          start_time?: string;
          status?: string;
          spread?: string;
          total?: string;
          moneyline_home?: string;
          moneyline_away?: string;
          spread_odds?: string;
          total_over_odds?: string;
          total_under_odds?: string;
          matchup?: string;
          away_team_meta?: Json;
          home_team_meta?: Json;
          home_odds?: number;
          away_odds?: number;
          home_spread?: number;
          away_spread?: number;
          home_spread_odds?: number;
          away_spread_odds?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sport?: string;
          league?: string;
          home_team_id?: string;
          away_team_id?: string;
          home_team?: string;
          away_team?: string;
          game_date?: string;
          game_time?: string;
          commence_time?: string;
          start_time?: string;
          status?: string;
          spread?: string;
          total?: string;
          moneyline_home?: string;
          moneyline_away?: string;
          spread_odds?: string;
          total_over_odds?: string;
          total_under_odds?: string;
          matchup?: string;
          away_team_meta?: Json;
          home_team_meta?: Json;
          home_odds?: number;
          away_odds?: number;
          home_spread?: number;
          away_spread?: number;
          home_spread_odds?: number;
          away_spread_odds?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      raw_props: {
        Row: {
          id: string;
          game_id: string;
          external_game_id?: string;
          player_id?: string;
          team_id?: string;
          player_name?: string;
          team?: string;
          opponent?: string;
          prop_type: string;
          stat_type?: string;
          market_type: string;
          line: number;
          odds: number;
          over_odds?: number;
          under_odds?: number;
          confidence?: number;
          expected_value?: number;
          provider?: string;
          sport?: string;
          game_time?: string;
          status: string;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          external_game_id?: string;
          player_id?: string;
          team_id?: string;
          player_name?: string;
          team?: string;
          opponent?: string;
          prop_type: string;
          stat_type?: string;
          market_type: string;
          line: number;
          odds: number;
          over_odds?: number;
          under_odds?: number;
          confidence?: number;
          expected_value?: number;
          provider?: string;
          sport?: string;
          game_time?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          external_game_id?: string;
          player_id?: string;
          team_id?: string;
          player_name?: string;
          team?: string;
          opponent?: string;
          prop_type?: string;
          stat_type?: string;
          market_type?: string;
          line?: number;
          odds?: number;
          over_odds?: number;
          under_odds?: number;
          confidence?: number;
          expected_value?: number;
          provider?: string;
          sport?: string;
          game_time?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tickets: {
        Row: {
          id: string;
          capper_id: string;
          ticket_type: string;
          unit_size: number;
          risk_amount: number;
          potential_payout: number;
          odds_format: string;
          auto_parlay: boolean;
          sport: string;
          game_date: string;
          confidence_level: number;
          user_tier: string;
          status: string;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          capper_id: string;
          ticket_type: string;
          unit_size: number;
          risk_amount: number;
          potential_payout: number;
          odds_format: string;
          auto_parlay: boolean;
          sport: string;
          game_date: string;
          confidence_level: number;
          user_tier: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          capper_id?: string;
          ticket_type?: string;
          unit_size?: number;
          risk_amount?: number;
          potential_payout?: number;
          odds_format?: string;
          auto_parlay?: boolean;
          sport?: string;
          game_date?: string;
          confidence_level?: number;
          user_tier?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          username: string;
          discord_id?: string;
          tier?: string;
          capper_tier?: string;
          active: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          username: string;
          discord_id?: string;
          tier?: string;
          capper_tier?: string;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          discord_id?: string;
          tier?: string;
          capper_tier?: string;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      bridge_outbox: {
        Row: {
          id: string;
          event_type: string;
          payload: Json;
          unique_key: string;
          status: string;
          attempts: number;
          max_attempts: number;
          next_attempt_at?: string;
          created_at?: string;
          updated_at?: string;
          processed_at?: string;
          error_message?: string;
        };
        Insert: {
          id?: string;
          event_type: string;
          payload: Json;
          unique_key: string;
          status?: string;
          attempts?: number;
          max_attempts?: number;
          next_attempt_at?: string;
          created_at?: string;
          updated_at?: string;
          processed_at?: string;
          error_message?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          payload?: Json;
          unique_key?: string;
          status?: string;
          attempts?: number;
          max_attempts?: number;
          next_attempt_at?: string;
          created_at?: string;
          updated_at?: string;
          processed_at?: string;
          error_message?: string;
        };
      };
      smart_tickets: {
        Row: {
          id: string;
          bet_slip_id: string;
          capper_id: string;
          sport: string;
          ticket_type: string;
          game_selections: Json;
          unit_size: number;
          odds_format: string;
          confidence_level: number;
          user_tier: string;
          status: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          bet_slip_id: string;
          capper_id: string;
          sport: string;
          ticket_type: string;
          game_selections: Json;
          unit_size: number;
          odds_format: string;
          confidence_level: number;
          user_tier: string;
          status?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bet_slip_id?: string;
          capper_id?: string;
          sport?: string;
          ticket_type?: string;
          game_selections?: Json;
          unit_size?: number;
          odds_format?: string;
          confidence_level?: number;
          user_tier?: string;
          status?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      unified_picks: {
        Row: {
          id: string;
          bet_slip_id: string;
          user_id: string;
          sport: string;
          stat_type: string;
          line: number;
          odds: number;
          selection: string;
          confidence: number;
          team_id?: string;
          player_id?: string;
          source: string;
          is_live: boolean;
          status: string;
          created_at?: string;
          updated_at?: string;
        };
        Insert: {
          id?: string;
          bet_slip_id: string;
          user_id: string;
          sport: string;
          stat_type: string;
          line: number;
          odds: number;
          selection: string;
          confidence: number;
          team_id?: string;
          player_id?: string;
          source: string;
          is_live: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bet_slip_id?: string;
          user_id?: string;
          sport?: string;
          stat_type?: string;
          line?: number;
          odds?: number;
          selection?: string;
          confidence?: number;
          team_id?: string;
          player_id?: string;
          source?: string;
          is_live?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
