import { Logger } from '../../shared/logger/types';
interface MarketInsight {
    insightId: string;
    type: 'trend' | 'anomaly' | 'opportunity' | 'risk' | 'pattern';
    severity: 'low' | 'medium' | 'high' | 'critical';
    description: string;
    affectedMarkets: string[];
    confidence: number;
    timeframe: string;
    actionable: boolean;
    recommendations: string[];
    historicalPrecedent?: string;
    timestamp: Date;
}
export declare class MarketForecaster {
    private readonly logger;
    private forecastingModels;
    private marketTrends;
    private detectedAnomalies;
    private identifiedOpportunities;
    private assessedRisks;
    private historicalPatterns;
    constructor(logger: Logger);
    initialize(): Promise<void>;
    detectTrends(): Promise<MarketInsight[]>;
    detectAnomalies(): Promise<MarketInsight[]>;
    identifyOpportunities(): Promise<MarketInsight[]>;
    assessMarketRisks(): Promise<MarketInsight[]>;
    forecastMarketMovement(marketId: string, timeHorizon: number): Promise<any>;
    private analyzeTrendForMarket;
    private analyzeAnomaliesForMarket;
    private identifyArbitrageOpportunities;
    private identifyValueBettingOpportunities;
    private identifyMarketInefficiencies;
    private identifyTrendReversalOpportunities;
    private assessLiquidityRisks;
    private assessVolatilityRisks;
    private assessCorrelationRisks;
    private assessSystematicRisks;
    private getRecentMarketData;
    private generateSampleMarketData;
    private calculateSMA;
    private calculateTrendStrength;
    private calculateRSquared;
    private calculateMomentum;
    private calculateVolatility;
    private calculateBaseline;
    private calculateTrendConfidence;
    private calculateTrendSeverity;
    private generateTrendDescription;
    private generateAnomalyDescription;
    private generateTrendRecommendations;
    private generateAnomalyRecommendations;
    private identifyTrendDrivers;
    private identifyAnomalyCauses;
    private assessAnomalyImpact;
    private findHistoricalPrecedent;
    private formatTimeframe;
    private getMarketHistory;
    private selectBestModel;
    private generateForecast;
    private loadForecastingModels;
    private loadHistoricalPatterns;
    private loadMarketTrends;
    private loadAnomalyHistory;
    isHealthy(): Promise<boolean>;
    cleanup(): Promise<void>;
}
export {};
//# sourceMappingURL=marketForecaster.d.ts.map