/**
 * Enhanced Supabase Types with Complete Schema Alignment
 * Updated to match Fortune 100-grade database structure
 * Includes all enhanced scoring metrics and professional capper features
 */
import { z } from 'zod';
export interface EnhancedRawProp {
    id: string;
    game_id: string;
    player_id: string;
    player_name: string;
    team: string;
    opponent: string;
    market: string;
    market_type: string;
    line: number;
    over: number;
    under: number;
    over_odds: number;
    under_odds: number;
    outcome?: 'win' | 'loss' | 'push' | null;
    promoted_to_picks: boolean;
    promoted_at?: string;
    trend_confidence?: number;
    edge_score?: number;
    matchup_quality?: number;
    expected_value?: number;
    sharp_money?: number;
    line_movement?: number;
    player_form?: number;
    injury_impact?: number;
    weather_impact?: number;
    market_intelligence?: number;
    volume_profile?: number;
    closing_line_value?: number;
    steam_detected: boolean;
    predicted_closing_line?: number;
    optimal_betting_time?: string;
    best_available_line?: number;
    best_book?: string;
    public_betting_percentage?: number;
    sharp_betting_percentage?: number;
    contrarian_opportunity: boolean;
    injury_timing_advantage?: number;
    cross_market_arbitrage?: number;
    player_fatigue?: number;
    venue_advantage?: number;
    referee_impact?: number;
    pace_impact?: number;
    motivational_factors?: number;
    correlation_risk?: number;
    volatility?: number;
    portfolio_impact?: number;
    bid_ask_spread?: number;
    data_completeness?: number;
    outlier_score?: number;
    consistency_score?: number;
    data_validation_score?: number;
    source: string;
    league: string;
    game_date?: string;
    created_at: string;
    updated_at: string;
    metadata?: Record<string, unknown>;
}
export declare const EnhancedRawPropSchema: z.ZodObject<{
    id: z.ZodString;
    game_id: z.ZodString;
    player_id: z.ZodString;
    player_name: z.ZodString;
    team: z.ZodString;
    opponent: z.ZodString;
    market: z.ZodString;
    market_type: z.ZodString;
    line: z.ZodNumber;
    over: z.ZodNumber;
    under: z.ZodNumber;
    over_odds: z.ZodNumber;
    under_odds: z.ZodNumber;
    outcome: z.ZodOptional<z.ZodNullable<z.ZodEnum<["win", "loss", "push"]>>>;
    promoted_to_picks: z.ZodDefault<z.ZodBoolean>;
    promoted_at: z.ZodOptional<z.ZodString>;
    trend_confidence: z.ZodOptional<z.ZodNumber>;
    edge_score: z.ZodOptional<z.ZodNumber>;
    matchup_quality: z.ZodOptional<z.ZodNumber>;
    expected_value: z.ZodOptional<z.ZodNumber>;
    sharp_money: z.ZodOptional<z.ZodNumber>;
    line_movement: z.ZodOptional<z.ZodNumber>;
    player_form: z.ZodOptional<z.ZodNumber>;
    injury_impact: z.ZodOptional<z.ZodNumber>;
    weather_impact: z.ZodOptional<z.ZodNumber>;
    market_intelligence: z.ZodOptional<z.ZodNumber>;
    volume_profile: z.ZodOptional<z.ZodNumber>;
    closing_line_value: z.ZodOptional<z.ZodNumber>;
    steam_detected: z.ZodDefault<z.ZodBoolean>;
    predicted_closing_line: z.ZodOptional<z.ZodNumber>;
    optimal_betting_time: z.ZodOptional<z.ZodString>;
    best_available_line: z.ZodOptional<z.ZodNumber>;
    best_book: z.ZodOptional<z.ZodString>;
    public_betting_percentage: z.ZodOptional<z.ZodNumber>;
    sharp_betting_percentage: z.ZodOptional<z.ZodNumber>;
    contrarian_opportunity: z.ZodDefault<z.ZodBoolean>;
    injury_timing_advantage: z.ZodOptional<z.ZodNumber>;
    cross_market_arbitrage: z.ZodOptional<z.ZodNumber>;
    player_fatigue: z.ZodOptional<z.ZodNumber>;
    venue_advantage: z.ZodOptional<z.ZodNumber>;
    referee_impact: z.ZodOptional<z.ZodNumber>;
    pace_impact: z.ZodOptional<z.ZodNumber>;
    motivational_factors: z.ZodOptional<z.ZodNumber>;
    correlation_risk: z.ZodOptional<z.ZodNumber>;
    volatility: z.ZodDefault<z.ZodNumber>;
    portfolio_impact: z.ZodOptional<z.ZodNumber>;
    bid_ask_spread: z.ZodDefault<z.ZodNumber>;
    data_completeness: z.ZodDefault<z.ZodNumber>;
    outlier_score: z.ZodDefault<z.ZodNumber>;
    consistency_score: z.ZodDefault<z.ZodNumber>;
    data_validation_score: z.ZodDefault<z.ZodNumber>;
    source: z.ZodDefault<z.ZodString>;
    league: z.ZodString;
    game_date: z.ZodOptional<z.ZodString>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    market: string;
    volatility: number;
    over: number;
    under: number;
    created_at: string;
    line: number;
    id: string;
    game_id: string;
    player_id: string;
    player_name: string;
    over_odds: number;
    under_odds: number;
    updated_at: string;
    team: string;
    source: string;
    opponent: string;
    market_type: string;
    league: string;
    promoted_to_picks: boolean;
    steam_detected: boolean;
    contrarian_opportunity: boolean;
    bid_ask_spread: number;
    data_completeness: number;
    outlier_score: number;
    consistency_score: number;
    data_validation_score: number;
    metadata?: Record<string, unknown> | undefined;
    volume_profile?: number | undefined;
    line_movement?: number | undefined;
    player_form?: number | undefined;
    weather_impact?: number | undefined;
    game_date?: string | undefined;
    outcome?: "push" | "win" | "loss" | null | undefined;
    trend_confidence?: number | undefined;
    matchup_quality?: number | undefined;
    edge_score?: number | undefined;
    promoted_at?: string | undefined;
    sharp_money?: number | undefined;
    closing_line_value?: number | undefined;
    injury_timing_advantage?: number | undefined;
    cross_market_arbitrage?: number | undefined;
    expected_value?: number | undefined;
    injury_impact?: number | undefined;
    best_available_line?: number | undefined;
    best_book?: string | undefined;
    public_betting_percentage?: number | undefined;
    sharp_betting_percentage?: number | undefined;
    correlation_risk?: number | undefined;
    market_intelligence?: number | undefined;
    predicted_closing_line?: number | undefined;
    optimal_betting_time?: string | undefined;
    player_fatigue?: number | undefined;
    venue_advantage?: number | undefined;
    referee_impact?: number | undefined;
    pace_impact?: number | undefined;
    motivational_factors?: number | undefined;
    portfolio_impact?: number | undefined;
}, {
    market: string;
    over: number;
    under: number;
    created_at: string;
    line: number;
    id: string;
    game_id: string;
    player_id: string;
    player_name: string;
    over_odds: number;
    under_odds: number;
    updated_at: string;
    team: string;
    opponent: string;
    market_type: string;
    league: string;
    metadata?: Record<string, unknown> | undefined;
    volatility?: number | undefined;
    volume_profile?: number | undefined;
    line_movement?: number | undefined;
    player_form?: number | undefined;
    source?: string | undefined;
    weather_impact?: number | undefined;
    game_date?: string | undefined;
    outcome?: "push" | "win" | "loss" | null | undefined;
    trend_confidence?: number | undefined;
    matchup_quality?: number | undefined;
    edge_score?: number | undefined;
    promoted_to_picks?: boolean | undefined;
    promoted_at?: string | undefined;
    steam_detected?: boolean | undefined;
    contrarian_opportunity?: boolean | undefined;
    sharp_money?: number | undefined;
    closing_line_value?: number | undefined;
    injury_timing_advantage?: number | undefined;
    cross_market_arbitrage?: number | undefined;
    expected_value?: number | undefined;
    bid_ask_spread?: number | undefined;
    data_completeness?: number | undefined;
    outlier_score?: number | undefined;
    consistency_score?: number | undefined;
    data_validation_score?: number | undefined;
    injury_impact?: number | undefined;
    best_available_line?: number | undefined;
    best_book?: string | undefined;
    public_betting_percentage?: number | undefined;
    sharp_betting_percentage?: number | undefined;
    correlation_risk?: number | undefined;
    market_intelligence?: number | undefined;
    predicted_closing_line?: number | undefined;
    optimal_betting_time?: string | undefined;
    player_fatigue?: number | undefined;
    venue_advantage?: number | undefined;
    referee_impact?: number | undefined;
    pace_impact?: number | undefined;
    motivational_factors?: number | undefined;
    portfolio_impact?: number | undefined;
}>;
export interface GradingResult {
    id: string;
    prop_id: string;
    final_score: number;
    confidence: number;
    tier: 'S' | 'A' | 'B' | 'C' | 'D';
    edge_score?: number;
    kelly_fraction?: number;
    position_size?: number;
    risk_score?: number;
    feature_contributions?: Record<string, unknown>;
    model_contributions?: Record<string, unknown>;
    scenario_analysis?: Record<string, unknown>;
    professional_insights?: Record<string, unknown>;
    enhanced_capper_analysis?: Record<string, unknown>;
    data_quality?: number;
    model_agreement?: number;
    historical_accuracy?: number;
    model_version?: string;
    config_used?: string;
    created_at: string;
    updated_at: string;
}
export declare const GradingResultSchema: z.ZodObject<{
    id: z.ZodString;
    prop_id: z.ZodString;
    final_score: z.ZodNumber;
    confidence: z.ZodNumber;
    tier: z.ZodEnum<["S", "A", "B", "C", "D"]>;
    edge_score: z.ZodOptional<z.ZodNumber>;
    kelly_fraction: z.ZodOptional<z.ZodNumber>;
    position_size: z.ZodOptional<z.ZodNumber>;
    risk_score: z.ZodOptional<z.ZodNumber>;
    feature_contributions: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    model_contributions: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    scenario_analysis: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    professional_insights: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    enhanced_capper_analysis: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    data_quality: z.ZodDefault<z.ZodNumber>;
    model_agreement: z.ZodOptional<z.ZodNumber>;
    historical_accuracy: z.ZodOptional<z.ZodNumber>;
    model_version: z.ZodOptional<z.ZodString>;
    config_used: z.ZodOptional<z.ZodString>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    confidence: number;
    tier: "A" | "B" | "C" | "D" | "S";
    created_at: string;
    id: string;
    updated_at: string;
    prop_id: string;
    data_quality: number;
    final_score: number;
    edge_score?: number | undefined;
    kelly_fraction?: number | undefined;
    feature_contributions?: Record<string, unknown> | undefined;
    model_agreement?: number | undefined;
    professional_insights?: Record<string, unknown> | undefined;
    position_size?: number | undefined;
    risk_score?: number | undefined;
    model_contributions?: Record<string, unknown> | undefined;
    scenario_analysis?: Record<string, unknown> | undefined;
    enhanced_capper_analysis?: Record<string, unknown> | undefined;
    historical_accuracy?: number | undefined;
    model_version?: string | undefined;
    config_used?: string | undefined;
}, {
    confidence: number;
    tier: "A" | "B" | "C" | "D" | "S";
    created_at: string;
    id: string;
    updated_at: string;
    prop_id: string;
    final_score: number;
    data_quality?: number | undefined;
    edge_score?: number | undefined;
    kelly_fraction?: number | undefined;
    feature_contributions?: Record<string, unknown> | undefined;
    model_agreement?: number | undefined;
    professional_insights?: Record<string, unknown> | undefined;
    position_size?: number | undefined;
    risk_score?: number | undefined;
    model_contributions?: Record<string, unknown> | undefined;
    scenario_analysis?: Record<string, unknown> | undefined;
    enhanced_capper_analysis?: Record<string, unknown> | undefined;
    historical_accuracy?: number | undefined;
    model_version?: string | undefined;
    config_used?: string | undefined;
}>;
export interface EnhancedUnifiedPick {
    id: string;
    raw_prop_id: string;
    grading_result_id?: string;
    player_name: string;
    market_type: string;
    line: number;
    odds: number;
    tier: 'S' | 'A' | 'B' | 'C' | 'D';
    confidence: number;
    score: number;
    edge_score?: number;
    position_size?: number;
    kelly_fraction?: number;
    risk_score?: number;
    play_status: 'pending' | 'approved' | 'rejected' | 'settled';
    result: 'win' | 'loss' | 'push' | 'pending';
    actual_result?: number;
    profit_loss?: number;
    settled_at?: string;
    created_at: string;
    updated_at: string;
}
export declare const EnhancedUnifiedPickSchema: z.ZodObject<{
    id: z.ZodString;
    raw_prop_id: z.ZodString;
    grading_result_id: z.ZodOptional<z.ZodString>;
    player_name: z.ZodString;
    market_type: z.ZodString;
    line: z.ZodNumber;
    odds: z.ZodNumber;
    tier: z.ZodEnum<["S", "A", "B", "C", "D"]>;
    confidence: z.ZodNumber;
    score: z.ZodNumber;
    edge_score: z.ZodOptional<z.ZodNumber>;
    position_size: z.ZodOptional<z.ZodNumber>;
    kelly_fraction: z.ZodOptional<z.ZodNumber>;
    risk_score: z.ZodOptional<z.ZodNumber>;
    play_status: z.ZodDefault<z.ZodEnum<["pending", "approved", "rejected", "settled"]>>;
    result: z.ZodDefault<z.ZodEnum<["win", "loss", "push", "pending"]>>;
    actual_result: z.ZodOptional<z.ZodNumber>;
    profit_loss: z.ZodOptional<z.ZodNumber>;
    settled_at: z.ZodOptional<z.ZodString>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    score: number;
    confidence: number;
    tier: "A" | "B" | "C" | "D" | "S";
    created_at: string;
    line: number;
    id: string;
    player_name: string;
    updated_at: string;
    raw_prop_id: string;
    result: "push" | "win" | "loss" | "pending";
    odds: number;
    market_type: string;
    play_status: "approved" | "settled" | "pending" | "rejected";
    settled_at?: string | undefined;
    edge_score?: number | undefined;
    kelly_fraction?: number | undefined;
    profit_loss?: number | undefined;
    position_size?: number | undefined;
    risk_score?: number | undefined;
    grading_result_id?: string | undefined;
    actual_result?: number | undefined;
}, {
    score: number;
    confidence: number;
    tier: "A" | "B" | "C" | "D" | "S";
    created_at: string;
    line: number;
    id: string;
    player_name: string;
    updated_at: string;
    raw_prop_id: string;
    odds: number;
    market_type: string;
    result?: "push" | "win" | "loss" | "pending" | undefined;
    settled_at?: string | undefined;
    edge_score?: number | undefined;
    kelly_fraction?: number | undefined;
    play_status?: "approved" | "settled" | "pending" | "rejected" | undefined;
    profit_loss?: number | undefined;
    position_size?: number | undefined;
    risk_score?: number | undefined;
    grading_result_id?: string | undefined;
    actual_result?: number | undefined;
}>;
export interface CapperProfile {
    id: string;
    discord_id: string;
    username: string;
    tier: 'bronze' | 'silver' | 'gold' | 'platinum' | 'vip' | 'vip_plus';
    total_picks: number;
    wins: number;
    losses: number;
    pushes: number;
    win_rate: number;
    roi: number;
    units_won: number;
    streak_current: number;
    streak_type: 'win' | 'loss' | 'none';
    created_at: string;
    updated_at: string;
}
export declare const CapperProfileSchema: z.ZodObject<{
    id: z.ZodString;
    discord_id: z.ZodString;
    username: z.ZodString;
    tier: z.ZodDefault<z.ZodEnum<["bronze", "silver", "gold", "platinum", "vip", "vip_plus"]>>;
    total_picks: z.ZodDefault<z.ZodNumber>;
    wins: z.ZodDefault<z.ZodNumber>;
    losses: z.ZodDefault<z.ZodNumber>;
    pushes: z.ZodDefault<z.ZodNumber>;
    win_rate: z.ZodNumber;
    roi: z.ZodDefault<z.ZodNumber>;
    units_won: z.ZodDefault<z.ZodNumber>;
    streak_current: z.ZodDefault<z.ZodNumber>;
    streak_type: z.ZodDefault<z.ZodEnum<["win", "loss", "none"]>>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    tier: "vip" | "vip_plus" | "bronze" | "silver" | "gold" | "platinum";
    roi: number;
    created_at: string;
    id: string;
    updated_at: string;
    discord_id: string;
    username: string;
    total_picks: number;
    win_rate: number;
    wins: number;
    losses: number;
    pushes: number;
    units_won: number;
    streak_current: number;
    streak_type: "win" | "loss" | "none";
}, {
    created_at: string;
    id: string;
    updated_at: string;
    discord_id: string;
    username: string;
    win_rate: number;
    tier?: "vip" | "vip_plus" | "bronze" | "silver" | "gold" | "platinum" | undefined;
    roi?: number | undefined;
    total_picks?: number | undefined;
    wins?: number | undefined;
    losses?: number | undefined;
    pushes?: number | undefined;
    units_won?: number | undefined;
    streak_current?: number | undefined;
    streak_type?: "win" | "loss" | "none" | undefined;
}>;
export interface MLFeatures {
    id: string;
    prop_id: string;
    neural_network_score?: number;
    gradient_boosting_score?: number;
    random_forest_score?: number;
    ensemble_score?: number;
    model_agreement?: number;
    feature_weights?: Record<string, unknown>;
    similar_props_performance?: Record<string, unknown>;
    player_historical_performance?: Record<string, unknown>;
    model_version?: string;
    created_at: string;
}
export declare const MLFeaturesSchema: z.ZodObject<{
    id: z.ZodString;
    prop_id: z.ZodString;
    neural_network_score: z.ZodOptional<z.ZodNumber>;
    gradient_boosting_score: z.ZodOptional<z.ZodNumber>;
    random_forest_score: z.ZodOptional<z.ZodNumber>;
    ensemble_score: z.ZodOptional<z.ZodNumber>;
    model_agreement: z.ZodOptional<z.ZodNumber>;
    feature_weights: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    similar_props_performance: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    player_historical_performance: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    model_version: z.ZodOptional<z.ZodString>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    created_at: string;
    id: string;
    prop_id: string;
    model_agreement?: number | undefined;
    feature_weights?: Record<string, unknown> | undefined;
    model_version?: string | undefined;
    neural_network_score?: number | undefined;
    gradient_boosting_score?: number | undefined;
    random_forest_score?: number | undefined;
    ensemble_score?: number | undefined;
    similar_props_performance?: Record<string, unknown> | undefined;
    player_historical_performance?: Record<string, unknown> | undefined;
}, {
    created_at: string;
    id: string;
    prop_id: string;
    model_agreement?: number | undefined;
    feature_weights?: Record<string, unknown> | undefined;
    model_version?: string | undefined;
    neural_network_score?: number | undefined;
    gradient_boosting_score?: number | undefined;
    random_forest_score?: number | undefined;
    ensemble_score?: number | undefined;
    similar_props_performance?: Record<string, unknown> | undefined;
    player_historical_performance?: Record<string, unknown> | undefined;
}>;
export interface SettlementTracking {
    id: string;
    pick_id: string;
    game_id?: string;
    settlement_source: string;
    original_line: number;
    actual_result?: number;
    settlement_status: 'pending' | 'settled' | 'void' | 'disputed';
    game_completed_at?: string;
    settlement_attempted_at?: string;
    settled_at?: string;
    settlement_errors?: Record<string, unknown>;
    retry_count: number;
    created_at: string;
    updated_at: string;
}
export declare const SettlementTrackingSchema: z.ZodObject<{
    id: z.ZodString;
    pick_id: z.ZodString;
    game_id: z.ZodOptional<z.ZodString>;
    settlement_source: z.ZodString;
    original_line: z.ZodNumber;
    actual_result: z.ZodOptional<z.ZodNumber>;
    settlement_status: z.ZodDefault<z.ZodEnum<["pending", "settled", "void", "disputed"]>>;
    game_completed_at: z.ZodOptional<z.ZodString>;
    settlement_attempted_at: z.ZodOptional<z.ZodString>;
    settled_at: z.ZodOptional<z.ZodString>;
    settlement_errors: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    retry_count: z.ZodDefault<z.ZodNumber>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    created_at: string;
    id: string;
    updated_at: string;
    original_line: number;
    settlement_status: "void" | "settled" | "pending" | "disputed";
    pick_id: string;
    retry_count: number;
    settlement_source: string;
    game_id?: string | undefined;
    settled_at?: string | undefined;
    actual_result?: number | undefined;
    game_completed_at?: string | undefined;
    settlement_attempted_at?: string | undefined;
    settlement_errors?: Record<string, unknown> | undefined;
}, {
    created_at: string;
    id: string;
    updated_at: string;
    original_line: number;
    pick_id: string;
    settlement_source: string;
    game_id?: string | undefined;
    settled_at?: string | undefined;
    settlement_status?: "void" | "settled" | "pending" | "disputed" | undefined;
    retry_count?: number | undefined;
    actual_result?: number | undefined;
    game_completed_at?: string | undefined;
    settlement_attempted_at?: string | undefined;
    settlement_errors?: Record<string, unknown> | undefined;
}>;
export interface Game {
    id: string;
    league: string;
    home_team: string;
    away_team: string;
    start_time: string;
    status: 'scheduled' | 'in_progress' | 'final' | 'postponed' | 'cancelled';
    created_at: string;
    updated_at: string;
}
export interface Team {
    id: string;
    name: string;
    league: string;
    created_at: string;
    updated_at: string;
}
export interface Player {
    id: string;
    name: string;
    team_id: string;
    position: string;
    created_at: string;
    updated_at: string;
}
export interface AgentLog {
    id: string;
    agent: string;
    level: string;
    message: string;
    context?: Record<string, unknown>;
    created_at: string;
    updated_at: string;
}
export interface AgentHealth {
    id: string;
    agent: string;
    status: 'healthy' | 'degraded' | 'unhealthy';
    details: Record<string, unknown>;
    created_at: string;
    updated_at: string;
}
export interface AgentMetrics {
    id: string;
    agent: string;
    metrics: Record<string, number>;
    created_at: string;
    updated_at: string;
}
export interface EnhancedTables {
    raw_props: {
        Row: EnhancedRawProp;
        Insert: Omit<EnhancedRawProp, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<EnhancedRawProp, 'id' | 'created_at'>>;
    };
    grading_results: {
        Row: GradingResult;
        Insert: Omit<GradingResult, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<GradingResult, 'id' | 'created_at'>>;
    };
    unified_picks: {
        Row: EnhancedUnifiedPick;
        Insert: Omit<EnhancedUnifiedPick, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<EnhancedUnifiedPick, 'id' | 'created_at'>>;
    };
    capper_profiles: {
        Row: CapperProfile;
        Insert: Omit<CapperProfile, 'id' | 'created_at' | 'updated_at' | 'win_rate'>;
        Update: Partial<Omit<CapperProfile, 'id' | 'created_at' | 'win_rate'>>;
    };
    ml_features: {
        Row: MLFeatures;
        Insert: Omit<MLFeatures, 'id' | 'created_at'>;
        Update: Partial<Omit<MLFeatures, 'id' | 'created_at'>>;
    };
    settlement_tracking: {
        Row: SettlementTracking;
        Insert: Omit<SettlementTracking, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<SettlementTracking, 'id' | 'created_at'>>;
    };
    games: {
        Row: Game;
        Insert: Omit<Game, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<Game, 'id' | 'created_at'>>;
    };
    teams: {
        Row: Team;
        Insert: Omit<Team, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<Team, 'id' | 'created_at'>>;
    };
    players: {
        Row: Player;
        Insert: Omit<Player, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<Player, 'id' | 'created_at'>>;
    };
    agent_logs: {
        Row: AgentLog;
        Insert: Omit<AgentLog, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<AgentLog, 'id' | 'created_at'>>;
    };
    agent_health: {
        Row: AgentHealth;
        Insert: Omit<AgentHealth, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<AgentHealth, 'id' | 'created_at'>>;
    };
    agent_metrics: {
        Row: AgentMetrics;
        Insert: Omit<AgentMetrics, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<AgentMetrics, 'id' | 'created_at'>>;
    };
}
export interface EnhancedDatabase {
    public: {
        Tables: EnhancedTables;
    };
}
export type TableRow<T extends keyof EnhancedTables> = EnhancedTables[T]['Row'];
export type TableInsert<T extends keyof EnhancedTables> = EnhancedTables[T]['Insert'];
export type TableUpdate<T extends keyof EnhancedTables> = EnhancedTables[T]['Update'];
export type RawProp = EnhancedRawProp;
export type UnifiedPick = EnhancedUnifiedPick;
export declare const VALIDATION_SCHEMAS: {
    readonly raw_props: z.ZodObject<{
        id: z.ZodString;
        game_id: z.ZodString;
        player_id: z.ZodString;
        player_name: z.ZodString;
        team: z.ZodString;
        opponent: z.ZodString;
        market: z.ZodString;
        market_type: z.ZodString;
        line: z.ZodNumber;
        over: z.ZodNumber;
        under: z.ZodNumber;
        over_odds: z.ZodNumber;
        under_odds: z.ZodNumber;
        outcome: z.ZodOptional<z.ZodNullable<z.ZodEnum<["win", "loss", "push"]>>>;
        promoted_to_picks: z.ZodDefault<z.ZodBoolean>;
        promoted_at: z.ZodOptional<z.ZodString>;
        trend_confidence: z.ZodOptional<z.ZodNumber>;
        edge_score: z.ZodOptional<z.ZodNumber>;
        matchup_quality: z.ZodOptional<z.ZodNumber>;
        expected_value: z.ZodOptional<z.ZodNumber>;
        sharp_money: z.ZodOptional<z.ZodNumber>;
        line_movement: z.ZodOptional<z.ZodNumber>;
        player_form: z.ZodOptional<z.ZodNumber>;
        injury_impact: z.ZodOptional<z.ZodNumber>;
        weather_impact: z.ZodOptional<z.ZodNumber>;
        market_intelligence: z.ZodOptional<z.ZodNumber>;
        volume_profile: z.ZodOptional<z.ZodNumber>;
        closing_line_value: z.ZodOptional<z.ZodNumber>;
        steam_detected: z.ZodDefault<z.ZodBoolean>;
        predicted_closing_line: z.ZodOptional<z.ZodNumber>;
        optimal_betting_time: z.ZodOptional<z.ZodString>;
        best_available_line: z.ZodOptional<z.ZodNumber>;
        best_book: z.ZodOptional<z.ZodString>;
        public_betting_percentage: z.ZodOptional<z.ZodNumber>;
        sharp_betting_percentage: z.ZodOptional<z.ZodNumber>;
        contrarian_opportunity: z.ZodDefault<z.ZodBoolean>;
        injury_timing_advantage: z.ZodOptional<z.ZodNumber>;
        cross_market_arbitrage: z.ZodOptional<z.ZodNumber>;
        player_fatigue: z.ZodOptional<z.ZodNumber>;
        venue_advantage: z.ZodOptional<z.ZodNumber>;
        referee_impact: z.ZodOptional<z.ZodNumber>;
        pace_impact: z.ZodOptional<z.ZodNumber>;
        motivational_factors: z.ZodOptional<z.ZodNumber>;
        correlation_risk: z.ZodOptional<z.ZodNumber>;
        volatility: z.ZodDefault<z.ZodNumber>;
        portfolio_impact: z.ZodOptional<z.ZodNumber>;
        bid_ask_spread: z.ZodDefault<z.ZodNumber>;
        data_completeness: z.ZodDefault<z.ZodNumber>;
        outlier_score: z.ZodDefault<z.ZodNumber>;
        consistency_score: z.ZodDefault<z.ZodNumber>;
        data_validation_score: z.ZodDefault<z.ZodNumber>;
        source: z.ZodDefault<z.ZodString>;
        league: z.ZodString;
        game_date: z.ZodOptional<z.ZodString>;
        created_at: z.ZodString;
        updated_at: z.ZodString;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        market: string;
        volatility: number;
        over: number;
        under: number;
        created_at: string;
        line: number;
        id: string;
        game_id: string;
        player_id: string;
        player_name: string;
        over_odds: number;
        under_odds: number;
        updated_at: string;
        team: string;
        source: string;
        opponent: string;
        market_type: string;
        league: string;
        promoted_to_picks: boolean;
        steam_detected: boolean;
        contrarian_opportunity: boolean;
        bid_ask_spread: number;
        data_completeness: number;
        outlier_score: number;
        consistency_score: number;
        data_validation_score: number;
        metadata?: Record<string, unknown> | undefined;
        volume_profile?: number | undefined;
        line_movement?: number | undefined;
        player_form?: number | undefined;
        weather_impact?: number | undefined;
        game_date?: string | undefined;
        outcome?: "push" | "win" | "loss" | null | undefined;
        trend_confidence?: number | undefined;
        matchup_quality?: number | undefined;
        edge_score?: number | undefined;
        promoted_at?: string | undefined;
        sharp_money?: number | undefined;
        closing_line_value?: number | undefined;
        injury_timing_advantage?: number | undefined;
        cross_market_arbitrage?: number | undefined;
        expected_value?: number | undefined;
        injury_impact?: number | undefined;
        best_available_line?: number | undefined;
        best_book?: string | undefined;
        public_betting_percentage?: number | undefined;
        sharp_betting_percentage?: number | undefined;
        correlation_risk?: number | undefined;
        market_intelligence?: number | undefined;
        predicted_closing_line?: number | undefined;
        optimal_betting_time?: string | undefined;
        player_fatigue?: number | undefined;
        venue_advantage?: number | undefined;
        referee_impact?: number | undefined;
        pace_impact?: number | undefined;
        motivational_factors?: number | undefined;
        portfolio_impact?: number | undefined;
    }, {
        market: string;
        over: number;
        under: number;
        created_at: string;
        line: number;
        id: string;
        game_id: string;
        player_id: string;
        player_name: string;
        over_odds: number;
        under_odds: number;
        updated_at: string;
        team: string;
        opponent: string;
        market_type: string;
        league: string;
        metadata?: Record<string, unknown> | undefined;
        volatility?: number | undefined;
        volume_profile?: number | undefined;
        line_movement?: number | undefined;
        player_form?: number | undefined;
        source?: string | undefined;
        weather_impact?: number | undefined;
        game_date?: string | undefined;
        outcome?: "push" | "win" | "loss" | null | undefined;
        trend_confidence?: number | undefined;
        matchup_quality?: number | undefined;
        edge_score?: number | undefined;
        promoted_to_picks?: boolean | undefined;
        promoted_at?: string | undefined;
        steam_detected?: boolean | undefined;
        contrarian_opportunity?: boolean | undefined;
        sharp_money?: number | undefined;
        closing_line_value?: number | undefined;
        injury_timing_advantage?: number | undefined;
        cross_market_arbitrage?: number | undefined;
        expected_value?: number | undefined;
        bid_ask_spread?: number | undefined;
        data_completeness?: number | undefined;
        outlier_score?: number | undefined;
        consistency_score?: number | undefined;
        data_validation_score?: number | undefined;
        injury_impact?: number | undefined;
        best_available_line?: number | undefined;
        best_book?: string | undefined;
        public_betting_percentage?: number | undefined;
        sharp_betting_percentage?: number | undefined;
        correlation_risk?: number | undefined;
        market_intelligence?: number | undefined;
        predicted_closing_line?: number | undefined;
        optimal_betting_time?: string | undefined;
        player_fatigue?: number | undefined;
        venue_advantage?: number | undefined;
        referee_impact?: number | undefined;
        pace_impact?: number | undefined;
        motivational_factors?: number | undefined;
        portfolio_impact?: number | undefined;
    }>;
    readonly grading_results: z.ZodObject<{
        id: z.ZodString;
        prop_id: z.ZodString;
        final_score: z.ZodNumber;
        confidence: z.ZodNumber;
        tier: z.ZodEnum<["S", "A", "B", "C", "D"]>;
        edge_score: z.ZodOptional<z.ZodNumber>;
        kelly_fraction: z.ZodOptional<z.ZodNumber>;
        position_size: z.ZodOptional<z.ZodNumber>;
        risk_score: z.ZodOptional<z.ZodNumber>;
        feature_contributions: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        model_contributions: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        scenario_analysis: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        professional_insights: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        enhanced_capper_analysis: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        data_quality: z.ZodDefault<z.ZodNumber>;
        model_agreement: z.ZodOptional<z.ZodNumber>;
        historical_accuracy: z.ZodOptional<z.ZodNumber>;
        model_version: z.ZodOptional<z.ZodString>;
        config_used: z.ZodOptional<z.ZodString>;
        created_at: z.ZodString;
        updated_at: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        confidence: number;
        tier: "A" | "B" | "C" | "D" | "S";
        created_at: string;
        id: string;
        updated_at: string;
        prop_id: string;
        data_quality: number;
        final_score: number;
        edge_score?: number | undefined;
        kelly_fraction?: number | undefined;
        feature_contributions?: Record<string, unknown> | undefined;
        model_agreement?: number | undefined;
        professional_insights?: Record<string, unknown> | undefined;
        position_size?: number | undefined;
        risk_score?: number | undefined;
        model_contributions?: Record<string, unknown> | undefined;
        scenario_analysis?: Record<string, unknown> | undefined;
        enhanced_capper_analysis?: Record<string, unknown> | undefined;
        historical_accuracy?: number | undefined;
        model_version?: string | undefined;
        config_used?: string | undefined;
    }, {
        confidence: number;
        tier: "A" | "B" | "C" | "D" | "S";
        created_at: string;
        id: string;
        updated_at: string;
        prop_id: string;
        final_score: number;
        data_quality?: number | undefined;
        edge_score?: number | undefined;
        kelly_fraction?: number | undefined;
        feature_contributions?: Record<string, unknown> | undefined;
        model_agreement?: number | undefined;
        professional_insights?: Record<string, unknown> | undefined;
        position_size?: number | undefined;
        risk_score?: number | undefined;
        model_contributions?: Record<string, unknown> | undefined;
        scenario_analysis?: Record<string, unknown> | undefined;
        enhanced_capper_analysis?: Record<string, unknown> | undefined;
        historical_accuracy?: number | undefined;
        model_version?: string | undefined;
        config_used?: string | undefined;
    }>;
    readonly unified_picks: z.ZodObject<{
        id: z.ZodString;
        raw_prop_id: z.ZodString;
        grading_result_id: z.ZodOptional<z.ZodString>;
        player_name: z.ZodString;
        market_type: z.ZodString;
        line: z.ZodNumber;
        odds: z.ZodNumber;
        tier: z.ZodEnum<["S", "A", "B", "C", "D"]>;
        confidence: z.ZodNumber;
        score: z.ZodNumber;
        edge_score: z.ZodOptional<z.ZodNumber>;
        position_size: z.ZodOptional<z.ZodNumber>;
        kelly_fraction: z.ZodOptional<z.ZodNumber>;
        risk_score: z.ZodOptional<z.ZodNumber>;
        play_status: z.ZodDefault<z.ZodEnum<["pending", "approved", "rejected", "settled"]>>;
        result: z.ZodDefault<z.ZodEnum<["win", "loss", "push", "pending"]>>;
        actual_result: z.ZodOptional<z.ZodNumber>;
        profit_loss: z.ZodOptional<z.ZodNumber>;
        settled_at: z.ZodOptional<z.ZodString>;
        created_at: z.ZodString;
        updated_at: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        score: number;
        confidence: number;
        tier: "A" | "B" | "C" | "D" | "S";
        created_at: string;
        line: number;
        id: string;
        player_name: string;
        updated_at: string;
        raw_prop_id: string;
        result: "push" | "win" | "loss" | "pending";
        odds: number;
        market_type: string;
        play_status: "approved" | "settled" | "pending" | "rejected";
        settled_at?: string | undefined;
        edge_score?: number | undefined;
        kelly_fraction?: number | undefined;
        profit_loss?: number | undefined;
        position_size?: number | undefined;
        risk_score?: number | undefined;
        grading_result_id?: string | undefined;
        actual_result?: number | undefined;
    }, {
        score: number;
        confidence: number;
        tier: "A" | "B" | "C" | "D" | "S";
        created_at: string;
        line: number;
        id: string;
        player_name: string;
        updated_at: string;
        raw_prop_id: string;
        odds: number;
        market_type: string;
        result?: "push" | "win" | "loss" | "pending" | undefined;
        settled_at?: string | undefined;
        edge_score?: number | undefined;
        kelly_fraction?: number | undefined;
        play_status?: "approved" | "settled" | "pending" | "rejected" | undefined;
        profit_loss?: number | undefined;
        position_size?: number | undefined;
        risk_score?: number | undefined;
        grading_result_id?: string | undefined;
        actual_result?: number | undefined;
    }>;
    readonly capper_profiles: z.ZodObject<{
        id: z.ZodString;
        discord_id: z.ZodString;
        username: z.ZodString;
        tier: z.ZodDefault<z.ZodEnum<["bronze", "silver", "gold", "platinum", "vip", "vip_plus"]>>;
        total_picks: z.ZodDefault<z.ZodNumber>;
        wins: z.ZodDefault<z.ZodNumber>;
        losses: z.ZodDefault<z.ZodNumber>;
        pushes: z.ZodDefault<z.ZodNumber>;
        win_rate: z.ZodNumber;
        roi: z.ZodDefault<z.ZodNumber>;
        units_won: z.ZodDefault<z.ZodNumber>;
        streak_current: z.ZodDefault<z.ZodNumber>;
        streak_type: z.ZodDefault<z.ZodEnum<["win", "loss", "none"]>>;
        created_at: z.ZodString;
        updated_at: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        tier: "vip" | "vip_plus" | "bronze" | "silver" | "gold" | "platinum";
        roi: number;
        created_at: string;
        id: string;
        updated_at: string;
        discord_id: string;
        username: string;
        total_picks: number;
        win_rate: number;
        wins: number;
        losses: number;
        pushes: number;
        units_won: number;
        streak_current: number;
        streak_type: "win" | "loss" | "none";
    }, {
        created_at: string;
        id: string;
        updated_at: string;
        discord_id: string;
        username: string;
        win_rate: number;
        tier?: "vip" | "vip_plus" | "bronze" | "silver" | "gold" | "platinum" | undefined;
        roi?: number | undefined;
        total_picks?: number | undefined;
        wins?: number | undefined;
        losses?: number | undefined;
        pushes?: number | undefined;
        units_won?: number | undefined;
        streak_current?: number | undefined;
        streak_type?: "win" | "loss" | "none" | undefined;
    }>;
    readonly ml_features: z.ZodObject<{
        id: z.ZodString;
        prop_id: z.ZodString;
        neural_network_score: z.ZodOptional<z.ZodNumber>;
        gradient_boosting_score: z.ZodOptional<z.ZodNumber>;
        random_forest_score: z.ZodOptional<z.ZodNumber>;
        ensemble_score: z.ZodOptional<z.ZodNumber>;
        model_agreement: z.ZodOptional<z.ZodNumber>;
        feature_weights: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        similar_props_performance: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        player_historical_performance: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        model_version: z.ZodOptional<z.ZodString>;
        created_at: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        created_at: string;
        id: string;
        prop_id: string;
        model_agreement?: number | undefined;
        feature_weights?: Record<string, unknown> | undefined;
        model_version?: string | undefined;
        neural_network_score?: number | undefined;
        gradient_boosting_score?: number | undefined;
        random_forest_score?: number | undefined;
        ensemble_score?: number | undefined;
        similar_props_performance?: Record<string, unknown> | undefined;
        player_historical_performance?: Record<string, unknown> | undefined;
    }, {
        created_at: string;
        id: string;
        prop_id: string;
        model_agreement?: number | undefined;
        feature_weights?: Record<string, unknown> | undefined;
        model_version?: string | undefined;
        neural_network_score?: number | undefined;
        gradient_boosting_score?: number | undefined;
        random_forest_score?: number | undefined;
        ensemble_score?: number | undefined;
        similar_props_performance?: Record<string, unknown> | undefined;
        player_historical_performance?: Record<string, unknown> | undefined;
    }>;
    readonly settlement_tracking: z.ZodObject<{
        id: z.ZodString;
        pick_id: z.ZodString;
        game_id: z.ZodOptional<z.ZodString>;
        settlement_source: z.ZodString;
        original_line: z.ZodNumber;
        actual_result: z.ZodOptional<z.ZodNumber>;
        settlement_status: z.ZodDefault<z.ZodEnum<["pending", "settled", "void", "disputed"]>>;
        game_completed_at: z.ZodOptional<z.ZodString>;
        settlement_attempted_at: z.ZodOptional<z.ZodString>;
        settled_at: z.ZodOptional<z.ZodString>;
        settlement_errors: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        retry_count: z.ZodDefault<z.ZodNumber>;
        created_at: z.ZodString;
        updated_at: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        created_at: string;
        id: string;
        updated_at: string;
        original_line: number;
        settlement_status: "void" | "settled" | "pending" | "disputed";
        pick_id: string;
        retry_count: number;
        settlement_source: string;
        game_id?: string | undefined;
        settled_at?: string | undefined;
        actual_result?: number | undefined;
        game_completed_at?: string | undefined;
        settlement_attempted_at?: string | undefined;
        settlement_errors?: Record<string, unknown> | undefined;
    }, {
        created_at: string;
        id: string;
        updated_at: string;
        original_line: number;
        pick_id: string;
        settlement_source: string;
        game_id?: string | undefined;
        settled_at?: string | undefined;
        settlement_status?: "void" | "settled" | "pending" | "disputed" | undefined;
        retry_count?: number | undefined;
        actual_result?: number | undefined;
        game_completed_at?: string | undefined;
        settlement_attempted_at?: string | undefined;
        settlement_errors?: Record<string, unknown> | undefined;
    }>;
};
//# sourceMappingURL=enhanced-supabase-types.d.ts.map