// AUTO-GENERATED BY CURSOR: BaseAgent core shared types
import { z } from 'zod';

/** Zod schema for canonical BaseAgent config */
export const BaseAgentConfigSchema = z.object({
  name: z.string(),
  version: z.string(),
  enabled: z.boolean(),
  logLevel: z.enum(['debug', 'info', 'warn', 'error']).default('info'),
  metrics: z.object({
    enabled: z.boolean().default(true),
    interval: z.number().min(5).default(60)            // seconds
  }),
  health: z.object({
    enabled: z.boolean().default(true),
    interval: z.number().min(5).default(30)            // seconds
  }),
  retry: z.object({
    maxRetries:   z.number().min(0).default(3),
    backoffMs:    z.number().min(100).default(200),
    maxBackoffMs: z.number().min(500).default(5000)
  })
});
export type BaseAgentConfig = z.infer<typeof BaseAgentConfigSchema>;

export type AgentStatus   =
  | 'idle' | 'initializing' | 'running'
  | 'stopping' | 'stopped' | 'error';

export interface BaseMetrics {
  successCount: number;
  errorCount:   number;
  warningCount: number;
  processingTimeMs: number;
  memoryUsageMb:    number;
  [key: `custom.${string}`]: unknown;
}

export interface HealthStatus {
  status: 'healthy' | 'degraded' | 'unhealthy';
  timestamp: string;
  details?: Record<string, unknown>;
}

/** DI bundle every agent receives */
export interface BaseAgentDependencies {
  supabase: import('@supabase/supabase-js').SupabaseClient;
  logger:   ReturnType<typeof import('../../utils/logger').createLogger>;
  errorHandler: import('../../utils/errorHandling').ErrorHandler;
} 