#!/usr/bin/env bash
# SPRINT-HULY-WORKOS-V1-LOCAL-001: First-time Huly setup
# Generates secrets and creates .env for docker compose

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$SCRIPT_DIR/../docker"
ENV_FILE="$DOCKER_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "WARNING: $ENV_FILE already exists."
  read -rp "Overwrite? [y/N] " confirm
  if [[ "$confirm" != [yY] ]]; then
    echo "Aborted."
    exit 0
  fi
fi

# Generate a random secret
SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p -c 64)

cat > "$ENV_FILE" <<EOF
# Generated by huly-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file

SECRET=${SECRET}
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
EOF

echo "Created $ENV_FILE with generated SECRET."
echo ""
echo "Next steps:"
echo "  1. cd $DOCKER_DIR && docker compose up -d"
echo "  2. Open http://localhost:8087"
echo "  3. Create an account and workspace via the Huly UI"
echo "  4. Update tools/huly-os/.env with your credentials"
